import 'package:flutter/widgets.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _prefKey = 'selected_language_name';

  static final ValueNotifier<String> currentLanguageNotifier =
      ValueNotifier<String>('English');

  static final List<Map<String, String>> supportedLanguages = [
    {'name': 'English', 'nativeName': 'English (US)', 'code': 'en', 'flag': '🇺🇸'},
    {'name': 'Urdu (اردو)', 'nativeName': 'اردو', 'code': 'ur', 'flag': '🇵🇰'},
    {'name': 'Spanish (Español)', 'nativeName': 'Español', 'code': 'es', 'flag': '🇪🇸'},
    {'name': 'French (Français)', 'nativeName': 'Français', 'code': 'fr', 'flag': '🇫🇷'},
    {'name': 'German (Deutsch)', 'nativeName': 'Deutsch', 'code': 'de', 'flag': '🇩🇪'},
    {'name': 'Italian (Italiano)', 'nativeName': 'Italiano', 'code': 'it', 'flag': '🇮🇹'},
    {'name': 'Chinese (中文)', 'nativeName': '简体中文', 'code': 'zh', 'flag': '🇨🇳'},
    {'name': 'Japanese (日本語)', 'nativeName': '日本語', 'code': 'ja', 'flag': '🇯🇵'},
    {'name': 'Korean (한국어)', 'nativeName': '한국어', 'code': 'ko', 'flag': '🇰🇷'},
    {'name': 'Turkish (Türkçe)', 'nativeName': 'Türkçe', 'code': 'tr', 'flag': '🇹🇷'},
  ];

  static Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_prefKey) ?? 'English';
    currentLanguageNotifier.value = saved;
  }

  static Future<void> setLanguage(String languageName) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, languageName);
    currentLanguageNotifier.value = languageName;
  }

  static bool isRtl([String? langName]) {
    final lang = langName ?? currentLanguageNotifier.value;
    final code = _getLangCode(lang);
    return code == 'ur' || code == 'ar';
  }

  static TextDirection get textDirection {
    return isRtl() ? TextDirection.rtl : TextDirection.ltr;
  }

  static String tr(String key) {
    final lang = currentLanguageNotifier.value;
    if (lang == 'English' || !_translations.containsKey(key)) {
      return key;
    }

    final langMap = _translations[key];
    if (langMap == null) return key;

    final langCode = _getLangCode(lang);
    return langMap[langCode] ?? key;
  }

  static String _getLangCode(String langName) {
    if (langName.contains('Urdu')) return 'ur';
    if (langName.contains('Spanish')) return 'es';
    if (langName.contains('French')) return 'fr';
    if (langName.contains('German')) return 'de';
    if (langName.contains('Italian')) return 'it';
    if (langName.contains('Portuguese')) return 'pt';
    if (langName.contains('Arabic')) return 'ar';
    if (langName.contains('Hindi')) return 'hi';
    if (langName.contains('Chinese')) return 'zh';
    if (langName.contains('Japanese')) return 'ja';
    if (langName.contains('Korean')) return 'ko';
    if (langName.contains('Russian')) return 'ru';
    if (langName.contains('Turkish')) return 'tr';
    return 'en';
  }

  static final Map<String, Map<String, String>> _translations = {
    'Water Tracker': {
      'es': 'Rastreador de Agua',
      'fr': 'Suivi de l\'Eau',
      'de': 'Wasser-Tracker',
      'it': 'Monitoraggio Acqua',
      'pt': 'Rastreador de Ãgua',
      'ar': 'ØªØªØ¨Ø¹ Ø§Ù„Ù…Ø§Ø¡',
      'hi': 'à¤œà¤² à¤Ÿà¥à¤°à¥ˆà¤•à¤°',
      'zh': 'é¥®æ°´è¿½è¸ª',
      'ja': 'æ°´åˆ†ãƒˆãƒ©ãƒƒã‚«ãƒ¼',
      'ko': 'ìˆ˜ë¶„ ì¶”ì ê¸°',
      'ru': 'ÐœÐ¾Ð½Ð¸Ñ‚Ð¾Ñ€Ð¸Ð½Ð³ Ð²Ð¾Ð´Ñ‹',
      'tr': 'Su Takibi',
    },
    'Profile': {
      'es': 'Perfil',
      'fr': 'Profil',
      'de': 'Profil',
      'it': 'Profilo',
      'pt': 'Perfil',
      'ar': 'Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
      'hi': 'à¤ªà¥à¤°à¥‹à¤«à¤¼à¤¾à¤‡à¤²',
      'zh': 'ä¸ªäººèµ„æ–™',
      'ja': 'ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«',
      'ko': 'í”„ë¡œí•„',
      'ru': 'ÐŸÑ€Ð¾Ñ„Ð¸Ð»ÑŒ',
      'tr': 'Profil',
    },
    'Home': {
      'es': 'Inicio',
      'fr': 'Accueil',
      'de': 'Startseite',
      'it': 'Home',
      'pt': 'InÃ­cio',
      'ar': 'Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©',
      'hi': 'à¤¹à¥‹à¤®',
      'zh': 'é¦–é¡µ',
      'ja': 'ãƒ›ãƒ¼ãƒ ',
      'ko': 'í™ˆ',
      'ru': 'Ð“Ð»Ð°Ð²Ð½Ð°Ñ',
      'tr': 'Ana Sayfa',
    },
    'Personal Information': {
      'es': 'InformaciÃ³n Personal',
      'fr': 'Informations Personnelles',
      'de': 'PersÃ¶nliche Angaben',
      'it': 'Informazioni Personali',
      'pt': 'InformaÃ§Ãµes Pessoais',
      'ar': 'Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø´Ø®ØµÙŠØ©',
      'hi': 'à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€',
      'zh': 'ä¸ªäººä¿¡æ¯',
      'ja': 'å€‹äººæƒ…å ±',
      'ko': 'ê°œì¸ ì •ë³´',
      'ru': 'Ð›Ð¸Ñ‡Ð½Ñ‹Ðµ Ð´Ð°Ð½Ð½Ñ‹Ðµ',
      'tr': 'KiÅŸisel Bilgiler',
    },
    'User History': {
      'es': 'Historial de Usuario',
      'fr': 'Historique Utilisateur',
      'de': 'Nutzerhistorie',
      'it': 'Cronologia Utente',
      'pt': 'HistÃ³rico do UsuÃ¡rio',
      'ar': 'Ø³Ø¬Ù„ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
      'hi': 'à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾ à¤•à¤¾ à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸',
      'zh': 'ç”¨æˆ·åŽ†å²',
      'ja': 'ãƒ¦ãƒ¼ã‚¶ãƒ¼å±¥æ­´',
      'ko': 'ì‚¬ìš©ìž ê¸°ë¡',
      'ru': 'Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ',
      'tr': 'KullanÄ±cÄ± GeÃ§miÅŸi',
    },
    'Language': {
      'es': 'Idioma',
      'fr': 'Langue',
      'de': 'Sprache',
      'it': 'Lingua',
      'pt': 'Idioma',
      'ar': 'Ø§Ù„Ù„ØºØ©',
      'hi': 'à¤­à¤¾à¤·à¤¾',
      'zh': 'è¯­è¨€',
      'ja': 'è¨€èªž',
      'ko': 'ì–¸ì–´',
      'ru': 'Ð¯Ð·Ñ‹Ðº',
      'tr': 'Dil',
    },
    'Invite Friends': {
      'es': 'Invitar Amigos',
      'fr': 'Inviter des Amis',
      'de': 'Freunde einladen',
      'it': 'Invita Amici',
      'pt': 'Convidar Amigos',
      'ar': 'Ø¯Ø¹ÙˆØ© Ø§Ù„Ø£ØµØ¯Ù‚Ø§Ø¡',
      'hi': 'à¤®à¤¿à¤¤à¥à¤°à¥‹à¤‚ à¤•à¥‹ à¤†à¤®à¤‚à¤¤à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'zh': 'é‚€è¯·æœ‹å‹',
      'ja': 'å‹é”ã‚’æ‹›å¾…',
      'ko': 'ì¹œêµ¬ ì´ˆëŒ€',
      'ru': 'ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ñ‚ÑŒ Ð´Ñ€ÑƒÐ·ÐµÐ¹',
      'tr': 'ArkadaÅŸlarÄ± Davet Et',
    },
    'Progress & Analytics': {
      'es': 'Progreso y AnalÃ­tica',
      'fr': 'ProgrÃ¨s et Analyses',
      'de': 'Fortschritt & Analysen',
      'it': 'Progressi e Analisi',
      'pt': 'Progresso e AnÃ¡lises',
      'ar': 'Ø§Ù„ØªÙ‚Ø¯Ù… ÙˆØ§Ù„ØªØ­Ù„ÙŠÙ„Ø§Øª',
      'hi': 'à¤ªà¥à¤°à¤—à¤¤à¤¿ à¤”à¤° à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£',
      'zh': 'è¿›åº¦ä¸Žåˆ†æž',
      'ja': 'é€²æ—ã¨åˆ†æž',
      'ko': 'ì§„í–‰ ìƒí™© ë° ë¶„ì„',
      'ru': 'ÐŸÑ€Ð¾Ð³Ñ€ÐµÑÑ Ð¸ Ð°Ð½Ð°Ð»Ð¸Ñ‚Ð¸ÐºÐ°',
      'tr': 'Ä°lerleme ve Analiz',
    },
    'Health Calculator': {
      'es': 'Calculadora de Salud',
      'fr': 'Calculateur de SantÃ©',
      'de': 'Gesundheits-Rechner',
      'it': 'Calcolatore Salute',
      'pt': 'Calculadora de SaÃºde',
      'ar': 'Ø­Ø§Ø³Ø¨Ø© Ø§Ù„ØµØ­Ø©',
      'hi': 'à¤¸à¥à¤µà¤¾à¤¸à¥à¤¥à¥à¤¯ à¤•à¥ˆà¤²à¤•à¥à¤²à¥‡à¤Ÿà¤°',
      'zh': 'å¥åº·è®¡ç®—å™¨',
      'ja': 'å¥åº·è¨ˆç®—æ©Ÿ',
      'ko': 'ê±´ê°• ê³„ì‚°ê¸°',
      'ru': 'ÐšÐ°Ð»ÑŒÐºÑƒÐ»ÑÑ‚Ð¾Ñ€ Ð·Ð´Ð¾Ñ€Ð¾Ð²ÑŒÑ',
      'tr': 'SaÄŸlÄ±k HesaplayÄ±cÄ±',
    },
    'Settings & Appearance': {
      'es': 'Ajustes y Apariencia',
      'fr': 'ParamÃ¨tres et Apparence',
      'de': 'Einstellungen & Erscheinungsbild',
      'it': 'Impostazioni e Aspetto',
      'pt': 'ConfiguraÃ§Ãµes e AparÃªncia',
      'ar': 'Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª ÙˆØ§Ù„Ù…Ø¸Ù‡Ø±',
      'hi': 'à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸ à¤”à¤° à¤¸à¥à¤µà¤°à¥‚à¤ª',
      'zh': 'è®¾ç½®ä¸Žå¤–è§‚',
      'ja': 'è¨­å®šã¨å¤–è¦³',
      'ko': 'ì„¤ì • ë° ëª¨ì–‘',
      'ru': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Ð¸ Ð²Ð½ÐµÑˆÐ½Ð¸Ð¹ Ð²Ð¸Ð´',
      'tr': 'Ayarlar ve GÃ¶rÃ¼nÃ¼m',
    },
    'Log Out': {
      'es': 'Cerrar SesiÃ³n',
      'fr': 'DÃ©connexion',
      'de': 'Abmelden',
      'it': 'Disconnettersi',
      'pt': 'Sair',
      'ar': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
      'hi': 'à¤²à¥‰à¤— à¤†à¤‰à¤Ÿ',
      'zh': 'é€€å‡ºç™»å½•',
      'ja': 'ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
      'ko': 'ë¡œê·¸ì•„ì›ƒ',
      'ru': 'Ð’Ñ‹Ð¹Ñ‚Ð¸',
      'tr': 'Ã‡Ä±kÄ±ÅŸ Yap',
    },
    'Weight': {
      'es': 'Peso',
      'fr': 'Poids',
      'de': 'Gewicht',
      'it': 'Peso',
      'pt': 'Peso',
      'ar': 'Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¼à¤¨',
      'zh': 'ä½“é‡',
      'ja': 'ä½“é‡',
      'ko': 'ì²´ì¤‘',
      'ru': 'Ð’ÐµÑ',
      'tr': 'Kilo',
    },
    'Height': {
      'es': 'Altura',
      'fr': 'Taille',
      'de': 'GrÃ¶ÃŸe',
      'it': 'Altezza',
      'pt': 'Altura',
      'ar': 'Ø§Ù„Ø·ÙˆÙ„',
      'hi': 'à¤Šà¤‚à¤šà¤¾à¤ˆ',
      'zh': 'èº«é«˜',
      'ja': 'èº«é•·',
      'ko': 'ì‹ ìž¥',
      'ru': 'Ð Ð¾ÑÑ‚',
      'tr': 'Boy',
    },
    'Target': {
      'es': 'Objetivo',
      'fr': 'Cible',
      'de': 'Ziel',
      'it': 'Obiettivo',
      'pt': 'Meta',
      'ar': 'Ø§Ù„Ù‡Ø¯Ù',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯',
      'zh': 'ç›®æ ‡',
      'ja': 'ç›®æ¨™',
      'ko': 'ëª©í‘œ',
      'ru': 'Ð¦ÐµÐ»ÑŒ',
      'tr': 'Hedef',
    },
    'Current': {
      'es': 'Actual',
      'fr': 'Actuel',
      'de': 'Aktuell',
      'it': 'Attuale',
      'pt': 'Atual',
      'ar': 'Ø§Ù„Ø­Ø§Ù„ÙŠ',
      'hi': 'à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨',
      'zh': 'å½“å‰',
      'ja': 'ç¾åœ¨',
      'ko': 'í˜„ìž¬',
      'ru': 'Ð¢ÐµÐºÑƒÑ‰Ð¸Ð¹',
      'tr': 'Mevcut',
    },
    // â”€â”€ Dashboard â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Daily Calories': {
      'es': 'CalorÃ­as Diarias',
      'fr': 'Calories JournaliÃ¨res',
      'de': 'TÃ¤gliche Kalorien',
      'it': 'Calorie Giornaliere',
      'pt': 'Calorias DiÃ¡rias',
      'ar': 'Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ© Ø§Ù„ÙŠÙˆÙ…ÙŠØ©',
      'hi': 'à¤¦à¥ˆà¤¨à¤¿à¤• à¤•à¥ˆà¤²à¥‹à¤°à¥€',
      'zh': 'æ¯æ—¥å¡è·¯é‡Œ',
      'ja': '1æ—¥ã®ã‚«ãƒ­ãƒªãƒ¼',
      'ko': 'ì¼ì¼ ì¹¼ë¡œë¦¬',
      'ru': 'Ð¡ÑƒÑ‚Ð¾Ñ‡Ð½Ñ‹Ðµ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¸',
      'tr': 'GÃ¼nlÃ¼k Kalori',
    },
    'Current Weight': {
      'es': 'Peso Actual',
      'fr': 'Poids Actuel',
      'de': 'Aktuelles Gewicht',
      'it': 'Peso Attuale',
      'pt': 'Peso Atual',
      'ar': 'Ø§Ù„ÙˆØ²Ù† Ø§Ù„Ø­Ø§Ù„ÙŠ',
      'hi': 'à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨ à¤µà¤œà¤¼à¤¨',
      'zh': 'å½“å‰ä½“é‡',
      'ja': 'ç¾åœ¨ã®ä½“é‡',
      'ko': 'í˜„ìž¬ ì²´ì¤‘',
      'ru': 'Ð¢ÐµÐºÑƒÑ‰Ð¸Ð¹ Ð²ÐµÑ',
      'tr': 'Mevcut Kilo',
    },
    'Target Weight': {
      'es': 'Peso Objetivo',
      'fr': 'Poids Cible',
      'de': 'Zielgewicht',
      'it': 'Peso Obiettivo',
      'pt': 'Peso Alvo',
      'ar': 'Ø§Ù„ÙˆØ²Ù† Ø§Ù„Ù…Ø³ØªÙ‡Ø¯Ù',
      'hi': 'à¤²à¤•à¥à¤·à¤¿à¤¤ à¤µà¤œà¤¨',
      'zh': 'ç›®æ ‡ä½“é‡',
      'ja': 'ç›®æ¨™ä½“é‡',
      'ko': 'ëª©í‘œ ì²´ì¤‘',
      'ru': 'Ð¦ÐµÐ»ÐµÐ²Ð¾Ð¹ Ð²ÐµÑ',
      'tr': 'Hedef Kilo',
    },
    'BMI': {
      'es': 'IMC',
      'fr': 'IMC',
      'de': 'BMI',
      'it': 'IMC',
      'pt': 'IMC',
      'ar': 'Ù…Ø¤Ø´Ø± ÙƒØªÙ„Ø© Ø§Ù„Ø¬Ø³Ù…',
      'hi': 'à¤¬à¥€à¤à¤®à¤†à¤ˆ',
      'zh': 'BMI',
      'ja': 'BMI',
      'ko': 'BMI',
      'ru': 'Ð˜ÐœÐ¢',
      'tr': 'VKÄ°',
    },
    'Your progress': {
      'es': 'Tu progreso',
      'fr': 'Votre progrÃ¨s',
      'de': 'Dein Fortschritt',
      'it': 'Il tuo progresso',
      'pt': 'Seu progresso',
      'ar': 'ØªÙ‚Ø¯Ù…Ùƒ',
      'hi': 'à¤†à¤ªà¤•à¥€ à¤ªà¥à¤°à¤—à¤¤à¤¿',
      'zh': 'ä½ çš„è¿›åº¦',
      'ja': 'ã‚ãªãŸã®é€²æ—',
      'ko': 'ì§„í–‰ ìƒí™©',
      'ru': 'Ð’Ð°Ñˆ Ð¿Ñ€Ð¾Ð³Ñ€ÐµÑÑ',
      'tr': 'Ä°lerlemeniz',
    },
    'kcal left': {
      'es': 'kcal restantes',
      'fr': 'kcal restantes',
      'de': 'kcal Ã¼brig',
      'it': 'kcal rimaste',
      'pt': 'kcal restantes',
      'ar': 'Ø³Ø¹Ø± Ø­Ø±Ø§Ø±ÙŠ Ù…ØªØ¨Ù‚ÙŠ',
      'hi': 'kcal à¤¬à¤šà¥‡',
      'zh': 'å‰©ä½™åƒå¡',
      'ja': 'kcal æ®‹ã‚Š',
      'ko': 'kcal ë‚¨ìŒ',
      'ru': 'ÐºÐºÐ°Ð» Ð¾ÑÑ‚Ð°Ð»Ð¾ÑÑŒ',
      'tr': 'kcal kaldÄ±',
    },
    'View history & analytics': {
      'es': 'Ver historial y anÃ¡lisis',
      'fr': 'Voir l\'historique et les analyses',
      'de': 'Verlauf & Analysen ansehen',
      'it': 'Visualizza cronologia e analisi',
      'pt': 'Ver histÃ³rico e anÃ¡lises',
      'ar': 'Ø¹Ø±Ø¶ Ø§Ù„Ø³Ø¬Ù„ ÙˆØ§Ù„ØªØ­Ù„ÙŠÙ„Ø§Øª',
      'hi': 'à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸ à¤”à¤° à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤¦à¥‡à¤–à¥‡à¤‚',
      'zh': 'æŸ¥çœ‹åŽ†å²è®°å½•ä¸Žåˆ†æž',
      'ja': 'å±¥æ­´ã¨åˆ†æžã‚’è¦‹ã‚‹',
      'ko': 'ê¸°ë¡ ë° ë¶„ì„ ë³´ê¸°',
      'ru': 'ÐŸÑ€Ð¾ÑÐ¼Ð¾Ñ‚Ñ€ Ð¸ÑÑ‚Ð¾Ñ€Ð¸Ð¸ Ð¸ Ð°Ð½Ð°Ð»Ð¸Ñ‚Ð¸ÐºÐ¸',
      'tr': 'GeÃ§miÅŸ ve analiz gÃ¶rÃ¼ntÃ¼le',
    },
    "Today's Nutrition": {
      'es': 'NutriciÃ³n de Hoy',
      'fr': 'Nutrition du Jour',
      'de': 'Heutige ErnÃ¤hrung',
      'it': 'Nutrizione di Oggi',
      'pt': 'NutriÃ§Ã£o de Hoje',
      'ar': 'ØªØºØ°ÙŠØ© Ø§Ù„ÙŠÙˆÙ…',
      'hi': 'à¤†à¤œ à¤•à¤¾ à¤ªà¥‹à¤·à¤£',
      'zh': 'ä»Šæ—¥è¥å…»',
      'ja': 'ä»Šæ—¥ã®æ „é¤Š',
      'ko': 'ì˜¤ëŠ˜ì˜ ì˜ì–‘',
      'ru': 'ÐŸÐ¸Ñ‚Ð°Ð½Ð¸Ðµ ÑÐµÐ³Ð¾Ð´Ð½Ñ',
      'tr': 'BugÃ¼nÃ¼n Besin DeÄŸerleri',
    },
    'Protein': {
      'es': 'ProteÃ­na',
      'fr': 'ProtÃ©ines',
      'de': 'Protein',
      'it': 'Proteine',
      'pt': 'ProteÃ­na',
      'ar': 'Ø§Ù„Ø¨Ø±ÙˆØªÙŠÙ†',
      'hi': 'à¤ªà¥à¤°à¥‹à¤Ÿà¥€à¤¨',
      'zh': 'è›‹ç™½è´¨',
      'ja': 'ã‚¿ãƒ³ãƒ‘ã‚¯è³ª',
      'ko': 'ë‹¨ë°±ì§ˆ',
      'ru': 'Ð‘ÐµÐ»Ð¾Ðº',
      'tr': 'Protein',
    },
    'Carbs': {
      'es': 'Carbohidratos',
      'fr': 'Glucides',
      'de': 'Kohlenhydrate',
      'it': 'Carboidrati',
      'pt': 'Carboidratos',
      'ar': 'Ø§Ù„ÙƒØ±Ø¨ÙˆÙ‡ÙŠØ¯Ø±Ø§Øª',
      'hi': 'à¤•à¤¾à¤°à¥à¤¬à¥‹à¤¹à¤¾à¤‡à¤¡à¥à¤°à¥‡à¤Ÿ',
      'zh': 'ç¢³æ°´åŒ–åˆç‰©',
      'ja': 'ç‚­æ°´åŒ–ç‰©',
      'ko': 'íƒ„ìˆ˜í™”ë¬¼',
      'ru': 'Ð£Ð³Ð»ÐµÐ²Ð¾Ð´Ñ‹',
      'tr': 'Karbonhidrat',
    },
    'Fat': {
      'es': 'Grasa',
      'fr': 'Graisses',
      'de': 'Fett',
      'it': 'Grassi',
      'pt': 'Gordura',
      'ar': 'Ø§Ù„Ø¯Ù‡ÙˆÙ†',
      'hi': 'à¤µà¤¸à¤¾',
      'zh': 'è„‚è‚ª',
      'ja': 'è„‚è³ª',
      'ko': 'ì§€ë°©',
      'ru': 'Ð–Ð¸Ñ€Ñ‹',
      'tr': 'YaÄŸ',
    },
    'Fats': {
      'es': 'Grasas',
      'fr': 'Lipides',
      'de': 'Fette',
      'it': 'Grassi',
      'pt': 'Gorduras',
      'ar': 'Ø§Ù„Ø¯Ù‡ÙˆÙ†',
      'hi': 'à¤µà¤¸à¤¾',
      'zh': 'è„‚è‚ª',
      'ja': 'è„‚è³ª',
      'ko': 'ì§€ë°©',
      'ru': 'Ð–Ð¸Ñ€Ñ‹',
      'tr': 'YaÄŸlar',
    },
    'Quick Actions': {
      'es': 'Acciones RÃ¡pidas',
      'fr': 'Actions Rapides',
      'de': 'Schnellaktionen',
      'it': 'Azioni Rapide',
      'pt': 'AÃ§Ãµes RÃ¡pidas',
      'ar': 'Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø³Ø±ÙŠØ¹Ø©',
      'hi': 'à¤¤à¥à¤µà¤°à¤¿à¤¤ à¤•à¥à¤°à¤¿à¤¯à¤¾à¤à¤‚',
      'zh': 'å¿«é€Ÿæ“ä½œ',
      'ja': 'ã‚¯ã‚¤ãƒƒã‚¯ã‚¢ã‚¯ã‚·ãƒ§ãƒ³',
      'ko': 'ë¹ ë¥¸ ìž‘ì—…',
      'ru': 'Ð‘Ñ‹ÑÑ‚Ñ€Ñ‹Ðµ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ',
      'tr': 'HÄ±zlÄ± Eylemler',
    },
    "Today's Meals": {
      'es': 'Comidas de Hoy',
      'fr': 'Repas du Jour',
      'de': 'Heutige Mahlzeiten',
      'it': 'Pasti di Oggi',
      'pt': 'RefeiÃ§Ãµes de Hoje',
      'ar': 'ÙˆØ¬Ø¨Ø§Øª Ø§Ù„ÙŠÙˆÙ…',
      'hi': 'à¤†à¤œ à¤•à¤¾ à¤­à¥‹à¤œà¤¨',
      'zh': 'ä»Šæ—¥é¤é£Ÿ',
      'ja': 'ä»Šæ—¥ã®é£Ÿäº‹',
      'ko': 'ì˜¤ëŠ˜ì˜ ì‹ì‚¬',
      'ru': 'Ð¡ÐµÐ³Ð¾Ð´Ð½ÑÑˆÐ½Ð¸Ðµ Ð±Ð»ÑŽÐ´Ð°',
      'tr': 'BugÃ¼nÃ¼n Ã–ÄŸÃ¼nleri',
    },
    "Yesterday's Meals": {
      'es': 'Comidas de Ayer',
      'fr': 'Repas d\'Hier',
      'de': 'Gestrige Mahlzeiten',
      'it': 'Pasti di Ieri',
      'pt': 'RefeiÃ§Ãµes de Ontem',
      'ar': 'ÙˆØ¬Ø¨Ø§Øª Ø§Ù„Ø£Ù…Ø³',
      'hi': 'à¤•à¤² à¤•à¤¾ à¤­à¥‹à¤œà¤¨',
      'zh': 'æ˜¨æ—¥é¤é£Ÿ',
      'ja': 'æ˜¨æ—¥ã®é£Ÿäº‹',
      'ko': 'ì–´ì œì˜ ì‹ì‚¬',
      'ru': 'Ð’Ñ‡ÐµÑ€Ð°ÑˆÐ½Ð¸Ðµ Ð±Ð»ÑŽÐ´Ð°',
      'tr': 'DÃ¼nÃ¼n Ã–ÄŸÃ¼nleri',
    },
    "Today's Entries": {
      'es': 'Entradas de Hoy',
      'fr': 'EntrÃ©es du Jour',
      'de': 'Heutige EintrÃ¤ge',
      'it': 'Voci di Oggi',
      'pt': 'Entradas de Hoje',
      'ar': 'Ø³Ø¬Ù„Ø§Øª Ø§Ù„ÙŠÙˆÙ…',
      'hi': 'à¤†à¤œ à¤•à¥€ à¤ªà¥à¤°à¤µà¤¿à¤·à¥à¤Ÿà¤¿à¤¯à¤¾à¤‚',
      'zh': 'ä»Šæ—¥è®°å½•',
      'ja': 'ä»Šæ—¥ã®ã‚¨ãƒ³ãƒˆãƒªãƒ¼',
      'ko': 'ì˜¤ëŠ˜ì˜ í•­ëª©',
      'ru': 'Ð¡ÐµÐ³Ð¾Ð´Ð½ÑÑˆÐ½Ð¸Ðµ Ð·Ð°Ð¿Ð¸ÑÐ¸',
      'tr': 'BugÃ¼nÃ¼n GiriÅŸleri',
    },
    'No meals added yet': {
      'es': 'AÃºn no se han agregado comidas',
      'fr': 'Aucun repas ajoutÃ© pour l\'instant',
      'de': 'Noch keine Mahlzeiten hinzugefÃ¼gt',
      'it': 'Nessun pasto aggiunto ancora',
      'pt': 'Nenhuma refeiÃ§Ã£o adicionada ainda',
      'ar': 'Ù„Ù… ØªÙØ¶Ù ÙˆØ¬Ø¨Ø§Øª Ø¨Ø¹Ø¯',
      'hi': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤­à¥‹à¤œà¤¨ à¤¨à¤¹à¥€à¤‚ à¤œà¥‹à¤¡à¤¼à¤¾ à¤—à¤¯à¤¾',
      'zh': 'å°šæœªæ·»åŠ é¤é£Ÿ',
      'ja': 'ã¾ã é£Ÿäº‹ãŒè¿½åŠ ã•ã‚Œã¦ã„ã¾ã›ã‚“',
      'ko': 'ì•„ì§ ì¶”ê°€ëœ ì‹ì‚¬ê°€ ì—†ìŠµë‹ˆë‹¤',
      'ru': 'Ð‘Ð»ÑŽÐ´Ð° ÐµÑ‰Ñ‘ Ð½Ðµ Ð´Ð¾Ð±Ð°Ð²Ð»ÐµÐ½Ñ‹',
      'tr': 'HenÃ¼z Ã¶ÄŸÃ¼n eklenmedi',
    },
    'Start by adding your first meal\nor scan it using AI.': {
      'es': 'Empieza aÃ±adiendo tu primera comida\no escanÃ©ala con IA.',
      'fr': 'Commencez par ajouter votre premier repas\nou scannez-le avec l\'IA.',
      'de': 'FÃ¼ge deine erste Mahlzeit hinzu\noder scanne sie mit KI.',
      'it': 'Inizia aggiungendo il tuo primo pasto\no scansionalo con l\'IA.',
      'pt': 'Comece adicionando sua primeira refeiÃ§Ã£o\nou digitalize-a com IA.',
      'ar': 'Ø§Ø¨Ø¯Ø£ Ø¨Ø¥Ø¶Ø§ÙØ© ÙˆØ¬Ø¨ØªÙƒ Ø§Ù„Ø£ÙˆÙ„Ù‰\nØ£Ùˆ Ø§Ù…Ø³Ø­Ù‡Ø§ Ø¶ÙˆØ¦ÙŠØ§Ù‹ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ.',
      'hi': 'à¤…à¤ªà¤¨à¤¾ à¤ªà¤¹à¤²à¤¾ à¤­à¥‹à¤œà¤¨ à¤œà¥‹à¤¡à¤¼à¤•à¤° à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚\nà¤¯à¤¾ AI à¤¸à¥‡ à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤°à¥‡à¤‚à¥¤',
      'zh': 'ä»Žæ·»åŠ æ‚¨çš„ç¬¬ä¸€é¤å¼€å§‹\næˆ–ä½¿ç”¨AIæ‰«æå®ƒã€‚',
      'ja': 'æœ€åˆã®é£Ÿäº‹ã‚’è¿½åŠ ã™ã‚‹ã‹\nAIã§ã‚¹ã‚­ãƒ£ãƒ³ã—ã¦ãã ã•ã„ã€‚',
      'ko': 'ì²« ë²ˆì§¸ ì‹ì‚¬ë¥¼ ì¶”ê°€í•˜ê±°ë‚˜\nAIë¡œ ìŠ¤ìº”í•˜ì„¸ìš”.',
      'ru': 'ÐÐ°Ñ‡Ð½Ð¸Ñ‚Ðµ Ñ Ð´Ð¾Ð±Ð°Ð²Ð»ÐµÐ½Ð¸Ñ Ð¿ÐµÑ€Ð²Ð¾Ð³Ð¾ Ð±Ð»ÑŽÐ´Ð°\nÐ¸Ð»Ð¸ Ð¾Ñ‚ÑÐºÐ°Ð½Ð¸Ñ€ÑƒÐ¹Ñ‚Ðµ ÐµÐ³Ð¾ Ñ Ð¿Ð¾Ð¼Ð¾Ñ‰ÑŒÑŽ Ð˜Ð˜.',
      'tr': 'Ä°lk Ã¶ÄŸÃ¼nÃ¼nÃ¼zÃ¼ ekleyerek baÅŸlayÄ±n\nveya AI ile tarayÄ±n.',
    },
    'Add': {
      'es': 'Agregar',
      'fr': 'Ajouter',
      'de': 'HinzufÃ¼gen',
      'it': 'Aggiungi',
      'pt': 'Adicionar',
      'ar': 'Ø¥Ø¶Ø§ÙØ©',
      'hi': 'à¤œà¥‹à¤¡à¤¼à¥‡à¤‚',
      'zh': 'æ·»åŠ ',
      'ja': 'è¿½åŠ ',
      'ko': 'ì¶”ê°€',
      'ru': 'Ð”Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ',
      'tr': 'Ekle',
    },
    'AI': {
      'es': 'IA',
      'fr': 'IA',
      'de': 'KI',
      'it': 'IA',
      'pt': 'IA',
      'ar': 'Ø°ÙƒØ§Ø¡ Ø§ØµØ·Ù†Ø§Ø¹ÙŠ',
      'hi': 'AI',
      'zh': 'AI',
      'ja': 'AI',
      'ko': 'AI',
      'ru': 'Ð˜Ð˜',
      'tr': 'YZ',
    },
    'Start your morning right': {
      'es': 'Comienza bien tu maÃ±ana',
      'fr': 'Commencez bien votre matinÃ©e',
      'de': 'Starte deinen Morgen richtig',
      'it': 'Inizia bene la tua mattina',
      'pt': 'Comece bem sua manhÃ£',
      'ar': 'Ø§Ø¨Ø¯Ø£ ØµØ¨Ø§Ø­Ùƒ Ø¨Ø´ÙƒÙ„ ØµØ­ÙŠØ­',
      'hi': 'à¤…à¤ªà¤¨à¥€ à¤¸à¥à¤¬à¤¹ à¤¸à¤¹à¥€ à¤¸à¥‡ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚',
      'zh': 'æ­£ç¡®å¼€å§‹æ‚¨çš„æ—©æ™¨',
      'ja': 'æœã‚’æ­£ã—ãå§‹ã‚ã¾ã—ã‚‡ã†',
      'ko': 'ì•„ì¹¨ì„ ì˜¬ë°”ë¥´ê²Œ ì‹œìž‘í•˜ì„¸ìš”',
      'ru': 'ÐÐ°Ñ‡Ð½Ð¸Ñ‚Ðµ ÑƒÑ‚Ñ€Ð¾ Ð¿Ñ€Ð°Ð²Ð¸Ð»ÑŒÐ½Ð¾',
      'tr': 'SabahÄ±nÄ±za doÄŸru baÅŸlayÄ±n',
    },
    'Recharge your energy': {
      'es': 'Recarga tu energÃ­a',
      'fr': 'Rechargez votre Ã©nergie',
      'de': 'Lade deine Energie auf',
      'it': 'Ricarica la tua energia',
      'pt': 'Recarregue sua energia',
      'ar': 'Ø£Ø¹Ø¯ Ø´Ø­Ù† Ø·Ø§Ù‚ØªÙƒ',
      'hi': 'à¤…à¤ªà¤¨à¥€ à¤Šà¤°à¥à¤œà¤¾ à¤•à¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚',
      'zh': 'è¡¥å……æ‚¨çš„èƒ½é‡',
      'ja': 'ã‚¨ãƒãƒ«ã‚®ãƒ¼ã‚’è£œå……ã—ã¾ã—ã‚‡ã†',
      'ko': 'ì—ë„ˆì§€ë¥¼ ì¶©ì „í•˜ì„¸ìš”',
      'ru': 'Ð’Ð¾ÑÐ¿Ð¾Ð»Ð½Ð¸Ñ‚Ðµ Ð·Ð°Ð¿Ð°Ñ ÑÐ½ÐµÑ€Ð³Ð¸Ð¸',
      'tr': 'Enerjinizi yenileyin',
    },
    'Finish the day healthy': {
      'es': 'Termina el dÃ­a saludable',
      'fr': 'Terminez la journÃ©e sainement',
      'de': 'Beende den Tag gesund',
      'it': 'Concludi la giornata in salute',
      'pt': 'Termine o dia saudÃ¡vel',
      'ar': 'Ø£Ù†Ù‡Ù ÙŠÙˆÙ…Ùƒ Ø¨ØµØ­Ø©',
      'hi': 'à¤¦à¤¿à¤¨ à¤•à¥‹ à¤¸à¥à¤µà¤¸à¥à¤¥ à¤°à¥‚à¤ª à¤¸à¥‡ à¤¸à¤®à¤¾à¤ªà¥à¤¤ à¤•à¤°à¥‡à¤‚',
      'zh': 'å¥åº·ç»“æŸä¸€å¤©',
      'ja': 'å¥åº·çš„ã«ä¸€æ—¥ã‚’çµ‚ãˆã¾ã—ã‚‡ã†',
      'ko': 'ê±´ê°•í•˜ê²Œ í•˜ë£¨ë¥¼ ë§ˆë¬´ë¦¬í•˜ì„¸ìš”',
      'ru': 'Ð—Ð°Ð²ÐµÑ€ÑˆÐ¸Ñ‚Ðµ Ð´ÐµÐ½ÑŒ Ð·Ð´Ð¾Ñ€Ð¾Ð²Ñ‹Ð¼',
      'tr': 'GÃ¼nÃ¼ saÄŸlÄ±klÄ± bitirin',
    },
    'Small bites & drinks': {
      'es': 'PequeÃ±os bocados y bebidas',
      'fr': 'Petites bouchÃ©es et boissons',
      'de': 'Kleine Snacks & GetrÃ¤nke',
      'it': 'Piccoli bocconi e bevande',
      'pt': 'Pequenas porÃ§Ãµes e bebidas',
      'ar': 'ÙˆØ¬Ø¨Ø§Øª Ø®ÙÙŠÙØ© ÙˆÙ…Ø´Ø±ÙˆØ¨Ø§Øª',
      'hi': 'à¤›à¥‹à¤Ÿà¥‡ à¤•à¤¾à¤Ÿà¤¨à¥‡ à¤”à¤° à¤ªà¥‡à¤¯',
      'zh': 'é›¶é£Ÿä¸Žé¥®æ–™',
      'ja': 'è»½é£Ÿã¨é£²ã¿ç‰©',
      'ko': 'ê°„ì‹ê³¼ ìŒë£Œ',
      'ru': 'ÐŸÐµÑ€ÐµÐºÑƒÑÑ‹ Ð¸ Ð½Ð°Ð¿Ð¸Ñ‚ÐºÐ¸',
      'tr': 'KÃ¼Ã§Ã¼k atÄ±ÅŸtÄ±rmalÄ±klar ve iÃ§ecekler',
    },
    'Water Intake': {
      'es': 'Ingesta de Agua',
      'fr': 'Consommation d\'Eau',
      'de': 'Wasseraufnahme',
      'it': 'Assunzione d\'Acqua',
      'pt': 'Consumo de Ãgua',
      'ar': 'Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ Ø§Ù„Ù…Ø§Ø¡',
      'hi': 'à¤œà¤² à¤¸à¥‡à¤µà¤¨',
      'zh': 'é¥®æ°´é‡',
      'ja': 'æ°´åˆ†æ‘‚å–é‡',
      'ko': 'ìˆ˜ë¶„ ì„­ì·¨ëŸ‰',
      'ru': 'ÐŸÐ¾Ñ‚Ñ€ÐµÐ±Ð»ÐµÐ½Ð¸Ðµ Ð²Ð¾Ð´Ñ‹',
      'tr': 'Su TÃ¼ketimi',
    },
    'Weight Goal': {
      'es': 'Objetivo de Peso',
      'fr': 'Objectif de Poids',
      'de': 'Gewichtsziel',
      'it': 'Obiettivo di Peso',
      'pt': 'Meta de Peso',
      'ar': 'Ù‡Ø¯Ù Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤²à¤•à¥à¤·à¥à¤¯',
      'zh': 'ä½“é‡ç›®æ ‡',
      'ja': 'ä½“é‡ç›®æ¨™',
      'ko': 'ì²´ì¤‘ ëª©í‘œ',
      'ru': 'Ð¦ÐµÐ»ÑŒ Ð¿Ð¾ Ð²ÐµÑÑƒ',
      'tr': 'Kilo Hedefi',
    },
    'AI Scan': {
      'es': 'Escaneo IA',
      'fr': 'Scan IA',
      'de': 'KI-Scan',
      'it': 'Scansione IA',
      'pt': 'Varredura IA',
      'ar': 'Ù…Ø³Ø­ Ø¨Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ',
      'hi': 'AI à¤¸à¥à¤•à¥ˆà¤¨',
      'zh': 'AI æ‰«æ',
      'ja': 'AIã‚¹ã‚­ãƒ£ãƒ³',
      'ko': 'AI ìŠ¤ìº”',
      'ru': 'Ð˜Ð˜-ÑÐºÐ°Ð½ÐµÑ€',
      'tr': 'AI Tarama',
    },
    'Calculator': {
      'es': 'Calculadora',
      'fr': 'Calculateur',
      'de': 'Rechner',
      'it': 'Calcolatore',
      'pt': 'Calculadora',
      'ar': 'Ø§Ù„Ø­Ø§Ø³Ø¨Ø©',
      'hi': 'à¤•à¥ˆà¤²à¤•à¥à¤²à¥‡à¤Ÿà¤°',
      'zh': 'è®¡ç®—å™¨',
      'ja': 'è¨ˆç®—æ©Ÿ',
      'ko': 'ê³„ì‚°ê¸°',
      'ru': 'ÐšÐ°Ð»ÑŒÐºÑƒÐ»ÑÑ‚Ð¾Ñ€',
      'tr': 'Hesap Makinesi',
    },
    'Breakfast': {
      'es': 'Desayuno',
      'fr': 'Petit-dÃ©jeuner',
      'de': 'FrÃ¼hstÃ¼ck',
      'it': 'Colazione',
      'pt': 'CafÃ© da ManhÃ£',
      'ar': 'Ø§Ù„Ø¥ÙØ·Ø§Ø±',
      'hi': 'à¤¨à¤¾à¤¶à¥à¤¤à¤¾',
      'zh': 'æ—©é¤',
      'ja': 'æœé£Ÿ',
      'ko': 'ì•„ì¹¨ ì‹ì‚¬',
      'ru': 'Ð—Ð°Ð²Ñ‚Ñ€Ð°Ðº',
      'tr': 'KahvaltÄ±',
    },
    'Lunch': {
      'es': 'Almuerzo',
      'fr': 'DÃ©jeuner',
      'de': 'Mittagessen',
      'it': 'Pranzo',
      'pt': 'AlmoÃ§o',
      'ar': 'Ø§Ù„ØºØ¯Ø§Ø¡',
      'hi': 'à¤¦à¥‹à¤ªà¤¹à¤° à¤•à¤¾ à¤­à¥‹à¤œà¤¨',
      'zh': 'åˆé¤',
      'ja': 'æ˜¼é£Ÿ',
      'ko': 'ì ì‹¬ ì‹ì‚¬',
      'ru': 'ÐžÐ±ÐµÐ´',
      'tr': 'Ã–ÄŸle YemeÄŸi',
    },
    'Dinner': {
      'es': 'Cena',
      'fr': 'DÃ®ner',
      'de': 'Abendessen',
      'it': 'Cena',
      'pt': 'Jantar',
      'ar': 'Ø§Ù„Ø¹Ø´Ø§Ø¡',
      'hi': 'à¤°à¤¾à¤¤ à¤•à¤¾ à¤­à¥‹à¤œà¤¨',
      'zh': 'æ™šé¤',
      'ja': 'å¤•é£Ÿ',
      'ko': 'ì €ë… ì‹ì‚¬',
      'ru': 'Ð£Ð¶Ð¸Ð½',
      'tr': 'AkÅŸam YemeÄŸi',
    },
    'Snacks': {
      'es': 'Meriendas',
      'fr': 'Collations',
      'de': 'Snacks',
      'it': 'Spuntini',
      'pt': 'Lanches',
      'ar': 'Ø§Ù„ÙˆØ¬Ø¨Ø§Øª Ø§Ù„Ø®ÙÙŠÙØ©',
      'hi': 'à¤¸à¥à¤¨à¥ˆà¤•à¥à¤¸',
      'zh': 'é›¶é£Ÿ',
      'ja': 'ã‚¹ãƒŠãƒƒã‚¯',
      'ko': 'ê°„ì‹',
      'ru': 'ÐŸÐµÑ€ÐµÐºÑƒÑÑ‹',
      'tr': 'AtÄ±ÅŸtÄ±rmalÄ±klar',
    },
    'Tap to view or log': {
      'es': 'Toca para ver o registrar',
      'fr': 'Appuyez pour voir ou enregistrer',
      'de': 'Tippen zum Anzeigen oder Protokollieren',
      'it': 'Tocca per visualizzare o registrare',
      'pt': 'Toque para ver ou registrar',
      'ar': 'Ø§Ø¶ØºØ· Ù„Ù„Ø¹Ø±Ø¶ Ø£Ùˆ Ø§Ù„ØªØ³Ø¬ÙŠÙ„',
      'hi': 'à¤¦à¥‡à¤–à¤¨à¥‡ à¤¯à¤¾ à¤²à¥‰à¤— à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚',
      'zh': 'ç‚¹å‡»æŸ¥çœ‹æˆ–è®°å½•',
      'ja': 'ã‚¿ãƒƒãƒ—ã—ã¦è¡¨ç¤ºã¾ãŸã¯è¨˜éŒ²',
      'ko': 'íƒ­í•˜ì—¬ ë³´ê±°ë‚˜ ê¸°ë¡',
      'ru': 'ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ Ð´Ð»Ñ Ð¿Ñ€Ð¾ÑÐ¼Ð¾Ñ‚Ñ€Ð° Ð¸Ð»Ð¸ Ð·Ð°Ð¿Ð¸ÑÐ¸',
      'tr': 'GÃ¶rÃ¼ntÃ¼lemek veya kaydetmek iÃ§in dokun',
    },
    'Tap to edit': {
      'es': 'Toca para editar',
      'fr': 'Appuyez pour modifier',
      'de': 'Tippen zum Bearbeiten',
      'it': 'Tocca per modificare',
      'pt': 'Toque para editar',
      'ar': 'Ø§Ø¶ØºØ· Ù„Ù„ØªØ¹Ø¯ÙŠÙ„',
      'hi': 'à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚',
      'zh': 'ç‚¹å‡»ç¼–è¾‘',
      'ja': 'ã‚¿ãƒƒãƒ—ã—ã¦ç·¨é›†',
      'ko': 'íƒ­í•˜ì—¬ ìˆ˜ì •',
      'ru': 'ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ Ð´Ð»Ñ Ñ€ÐµÐ´Ð°ÐºÑ‚Ð¸Ñ€Ð¾Ð²Ð°Ð½Ð¸Ñ',
      'tr': 'DÃ¼zenlemek iÃ§in dokun',
    },
    "Let's reach today's goal!": {
      'es': 'Â¡Alcancemos la meta de hoy!',
      'fr': 'Atteignons l\'objectif d\'aujourd\'hui !',
      'de': 'Lass uns das heutige Ziel erreichen!',
      'it': 'Raggiungiamo l\'obiettivo di oggi!',
      'pt': 'Vamos alcanÃ§ar a meta de hoje!',
      'ar': 'Ù„Ù†ØµÙ„ Ø¥Ù„Ù‰ Ù‡Ø¯Ù Ø§Ù„ÙŠÙˆÙ…!',
      'hi': 'à¤†à¤œ à¤•à¥‡ à¤²à¤•à¥à¤·à¥à¤¯ à¤•à¥‹ à¤ªà¥‚à¤°à¤¾ à¤•à¤°à¥‡à¤‚!',
      'zh': 'è®©æˆ‘ä»¬è¾¾æˆä»Šæ—¥ç›®æ ‡ï¼',
      'ja': 'ä»Šæ—¥ã®ç›®æ¨™ã‚’é”æˆã—ã¾ã—ã‚‡ã†ï¼',
      'ko': 'ì˜¤ëŠ˜ì˜ ëª©í‘œë¥¼ ë‹¬ì„±í•´ë´ìš”!',
      'ru': 'Ð”Ð¾ÑÑ‚Ð¸Ð³Ð½ÐµÐ¼ ÑÐµÐ³Ð¾Ð´Ð½ÑÑˆÐ½ÐµÐ¹ Ñ†ÐµÐ»Ð¸!',
      'tr': 'BugÃ¼nÃ¼n hedefine ulaÅŸalÄ±m!',
    },
    // â”€â”€ Water Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Daily Goal': {
      'es': 'Meta Diaria',
      'fr': 'Objectif Quotidien',
      'de': 'Tagesziel',
      'it': 'Obiettivo Giornaliero',
      'pt': 'Meta DiÃ¡ria',
      'ar': 'Ø§Ù„Ù‡Ø¯Ù Ø§Ù„ÙŠÙˆÙ…ÙŠ',
      'hi': 'à¤¦à¥ˆà¤¨à¤¿à¤• à¤²à¤•à¥à¤·à¥à¤¯',
      'zh': 'æ¯æ—¥ç›®æ ‡',
      'ja': '1æ—¥ã®ç›®æ¨™',
      'ko': 'ì¼ì¼ ëª©í‘œ',
      'ru': 'Ð”Ð½ÐµÐ²Ð½Ð°Ñ Ñ†ÐµÐ»ÑŒ',
      'tr': 'GÃ¼nlÃ¼k Hedef',
    },
    'Add Water': {
      'es': 'Agregar Agua',
      'fr': 'Ajouter de l\'Eau',
      'de': 'Wasser hinzufÃ¼gen',
      'it': 'Aggiungi Acqua',
      'pt': 'Adicionar Ãgua',
      'ar': 'Ø¥Ø¶Ø§ÙØ© Ù…Ø§Ø¡',
      'hi': 'à¤ªà¤¾à¤¨à¥€ à¤œà¥‹à¤¡à¤¼à¥‡à¤‚',
      'zh': 'æ·»åŠ é¥®æ°´',
      'ja': 'æ°´ã‚’è¿½åŠ ',
      'ko': 'ë¬¼ ì¶”ê°€',
      'ru': 'Ð”Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ Ð²Ð¾Ð´Ñƒ',
      'tr': 'Su Ekle',
    },
    'Weekly Overview': {
      'es': 'Resumen Semanal',
      'fr': 'AperÃ§u Hebdomadaire',
      'de': 'WochensÃ¼bersicht',
      'it': 'Panoramica Settimanale',
      'pt': 'VisÃ£o Semanal',
      'ar': 'Ù†Ø¸Ø±Ø© Ø£Ø³Ø¨ÙˆØ¹ÙŠØ©',
      'hi': 'à¤¸à¤¾à¤ªà¥à¤¤à¤¾à¤¹à¤¿à¤• à¤…à¤µà¤²à¥‹à¤•à¤¨',
      'zh': 'æ¯å‘¨æ¦‚è§ˆ',
      'ja': 'é€±é–“æ¦‚è¦',
      'ko': 'ì£¼ê°„ ê°œìš”',
      'ru': 'ÐžÐ±Ð·Ð¾Ñ€ Ð·Ð° Ð½ÐµÐ´ÐµÐ»ÑŽ',
      'tr': 'HaftalÄ±k Genel BakÄ±ÅŸ',
    },
    'Hydration History': {
      'es': 'Historial de HidrataciÃ³n',
      'fr': 'Historique d\'Hydratation',
      'de': 'Trinkprotokoll',
      'it': 'Cronologia Idratazione',
      'pt': 'HistÃ³rico de HidrataÃ§Ã£o',
      'ar': 'Ø³Ø¬Ù„ Ø§Ù„ØªØ±Ø·ÙŠØ¨',
      'hi': 'à¤œà¤²à¤¯à¥‹à¤œà¤¨ à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸',
      'zh': 'é¥®æ°´è®°å½•',
      'ja': 'æ°´åˆ†è£œçµ¦å±¥æ­´',
      'ko': 'ìˆ˜ë¶„ ì„­ì·¨ ê¸°ë¡',
      'ru': 'Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ Ð³Ð¸Ð´Ñ€Ð°Ñ‚Ð°Ñ†Ð¸Ð¸',
      'tr': 'Hidrasyon GeÃ§miÅŸi',
    },
    'Consumed': {
      'es': 'Consumido',
      'fr': 'ConsommÃ©',
      'de': 'Getrunken',
      'it': 'Consumato',
      'pt': 'Consumido',
      'ar': 'Ù…Ø³ØªÙ‡Ù„Ùƒ',
      'hi': 'à¤¸à¥‡à¤µà¤¨ à¤•à¤¿à¤¯à¤¾',
      'zh': 'å·²é¥®',
      'ja': 'æ‘‚å–æ¸ˆã¿',
      'ko': 'ì„­ì·¨ëŸ‰',
      'ru': 'ÐŸÐ¾Ñ‚Ñ€ÐµÐ±Ð»ÐµÐ½Ð¾',
      'tr': 'TÃ¼ketilen',
    },
    'Remaining': {
      'es': 'Restante',
      'fr': 'Restant',
      'de': 'Verbleibend',
      'it': 'Rimanente',
      'pt': 'Restante',
      'ar': 'Ø§Ù„Ù…ØªØ¨Ù‚ÙŠ',
      'hi': 'à¤¶à¥‡à¤·',
      'zh': 'å‰©ä½™',
      'ja': 'æ®‹ã‚Š',
      'ko': 'ë‚¨ì€ ì–‘',
      'ru': 'ÐžÑÑ‚Ð°Ð»Ð¾ÑÑŒ',
      'tr': 'Kalan',
    },
    // â”€â”€ Progress Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Progress & Weight': {
      'es': 'Progreso y Peso',
      'fr': 'ProgrÃ¨s et Poids',
      'de': 'Fortschritt & Gewicht',
      'it': 'Progressi e Peso',
      'pt': 'Progresso e Peso',
      'ar': 'Ø§Ù„ØªÙ‚Ø¯Ù… ÙˆØ§Ù„ÙˆØ²Ù†',
      'hi': 'à¤ªà¥à¤°à¤—à¤¤à¤¿ à¤”à¤° à¤µà¤œà¤¼à¤¨',
      'zh': 'è¿›åº¦ä¸Žä½“é‡',
      'ja': 'é€²æ—ã¨ä½“é‡',
      'ko': 'ì§„í–‰ ìƒí™© ë° ì²´ì¤‘',
      'ru': 'ÐŸÑ€Ð¾Ð³Ñ€ÐµÑÑ Ð¸ Ð²ÐµÑ',
      'tr': 'Ä°lerleme ve Kilo',
    },
    'Log Weight': {
      'es': 'Registrar Peso',
      'fr': 'Enregistrer le Poids',
      'de': 'Gewicht erfassen',
      'it': 'Registra Peso',
      'pt': 'Registrar Peso',
      'ar': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚',
      'zh': 'è®°å½•ä½“é‡',
      'ja': 'ä½“é‡ã‚’è¨˜éŒ²',
      'ko': 'ì²´ì¤‘ ê¸°ë¡',
      'ru': 'Ð—Ð°Ð¿Ð¸ÑÐ°Ñ‚ÑŒ Ð²ÐµÑ',
      'tr': 'Kilo Kaydet',
    },
    'Edit Target Weight': {
      'es': 'Editar Peso Objetivo',
      'fr': 'Modifier le Poids Cible',
      'de': 'Zielgewicht bearbeiten',
      'it': 'Modifica Peso Obiettivo',
      'pt': 'Editar Peso Alvo',
      'ar': 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„ÙˆØ²Ù† Ø§Ù„Ù…Ø³ØªÙ‡Ø¯Ù',
      'hi': 'à¤²à¤•à¥à¤·à¤¿à¤¤ à¤µà¤œà¤¨ à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'zh': 'ç¼–è¾‘ç›®æ ‡ä½“é‡',
      'ja': 'ç›®æ¨™ä½“é‡ã‚’ç·¨é›†',
      'ko': 'ëª©í‘œ ì²´ì¤‘ ìˆ˜ì •',
      'ru': 'Ð˜Ð·Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ñ†ÐµÐ»ÐµÐ²Ð¾Ð¹ Ð²ÐµÑ',
      'tr': 'Hedef Kiloyu DÃ¼zenle',
    },
    'Goal Progress': {
      'es': 'Progreso del Objetivo',
      'fr': 'Progression vers l\'objectif',
      'de': 'Zielfortschritt',
      'it': 'Progresso dell\'Obiettivo',
      'pt': 'Progresso da Meta',
      'ar': 'ØªÙ‚Ø¯Ù… Ø§Ù„Ù‡Ø¯Ù',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯ à¤ªà¥à¤°à¤—à¤¤à¤¿',
      'zh': 'ç›®æ ‡è¿›åº¦',
      'ja': 'ç›®æ¨™é€²æ—',
      'ko': 'ëª©í‘œ ì§„í–‰ ìƒí™©',
      'ru': 'ÐŸÑ€Ð¾Ð³Ñ€ÐµÑÑ Ðº Ñ†ÐµÐ»Ð¸',
      'tr': 'Hedef Ä°lerlemesi',
    },
    'Weight Chart': {
      'es': 'GrÃ¡fico de Peso',
      'fr': 'Graphique de Poids',
      'de': 'Gewichtsdiagramm',
      'it': 'Grafico del Peso',
      'pt': 'GrÃ¡fico de Peso',
      'ar': 'Ù…Ø®Ø·Ø· Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤šà¤¾à¤°à¥à¤Ÿ',
      'zh': 'ä½“é‡å›¾è¡¨',
      'ja': 'ä½“é‡ã‚°ãƒ©ãƒ•',
      'ko': 'ì²´ì¤‘ ì°¨íŠ¸',
      'ru': 'Ð“Ñ€Ð°Ñ„Ð¸Ðº Ð²ÐµÑÐ°',
      'tr': 'Kilo GrafiÄŸi',
    },
    'Weight History': {
      'es': 'Historial de Peso',
      'fr': 'Historique de Poids',
      'de': 'Gewichtsverlauf',
      'it': 'Cronologia del Peso',
      'pt': 'HistÃ³rico de Peso',
      'ar': 'Ø³Ø¬Ù„ Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸',
      'zh': 'ä½“é‡åŽ†å²',
      'ja': 'ä½“é‡å±¥æ­´',
      'ko': 'ì²´ì¤‘ ê¸°ë¡',
      'ru': 'Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ Ð²ÐµÑÐ°',
      'tr': 'Kilo GeÃ§miÅŸi',
    },
    'Log at least 2 weight entries to view graph.': {
      'es': 'Registra al menos 2 entradas de peso para ver el grÃ¡fico.',
      'fr': 'Enregistrez au moins 2 entrÃ©es de poids pour voir le graphique.',
      'de': 'Erfasse mindestens 2 GewichtseintrÃ¤ge, um das Diagramm zu sehen.',
      'it': 'Registra almeno 2 voci di peso per visualizzare il grafico.',
      'pt': 'Registre pelo menos 2 entradas de peso para ver o grÃ¡fico.',
      'ar': 'Ø³Ø¬Ù‘Ù„ Ø¥Ø¯Ø®Ø§Ù„ÙŽÙŠ ÙˆØ²Ù† Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„ Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø±Ø³Ù… Ø§Ù„Ø¨ÙŠØ§Ù†ÙŠ.',
      'hi': 'à¤—à¥à¤°à¤¾à¤« à¤¦à¥‡à¤–à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¤® à¤¸à¥‡ à¤•à¤® 2 à¤µà¤œà¤¨ à¤ªà¥à¤°à¤µà¤¿à¤·à¥à¤Ÿà¤¿à¤¯à¤¾à¤‚ à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚à¥¤',
      'zh': 'è‡³å°‘è®°å½•2æ¡ä½“é‡æ•°æ®æ‰èƒ½æŸ¥çœ‹å›¾è¡¨ã€‚',
      'ja': 'ã‚°ãƒ©ãƒ•ã‚’è¡¨ç¤ºã™ã‚‹ã«ã¯å°‘ãªãã¨ã‚‚2ã¤ã®ä½“é‡è¨˜éŒ²ãŒå¿…è¦ã§ã™ã€‚',
      'ko': 'ê·¸ëž˜í”„ë¥¼ ë³´ë ¤ë©´ ìµœì†Œ 2ê°œì˜ ì²´ì¤‘ í•­ëª©ì„ ê¸°ë¡í•˜ì„¸ìš”.',
      'ru': 'Ð—Ð°Ð¿Ð¸ÑˆÐ¸Ñ‚Ðµ Ð½Ðµ Ð¼ÐµÐ½ÐµÐµ 2 Ð·Ð°Ð¿Ð¸ÑÐµÐ¹ Ð²ÐµÑÐ°, Ñ‡Ñ‚Ð¾Ð±Ñ‹ ÑƒÐ²Ð¸Ð´ÐµÑ‚ÑŒ Ð³Ñ€Ð°Ñ„Ð¸Ðº.',
      'tr': 'GrafiÄŸi gÃ¶rmek iÃ§in en az 2 kilo giriÅŸi kaydedin.',
    },
    'No weight entries logged yet.': {
      'es': 'AÃºn no se han registrado entradas de peso.',
      'fr': 'Aucune entrÃ©e de poids enregistrÃ©e pour l\'instant.',
      'de': 'Noch keine GewichtseintrÃ¤ge erfasst.',
      'it': 'Nessuna voce di peso registrata ancora.',
      'pt': 'Nenhuma entrada de peso registrada ainda.',
      'ar': 'Ù„Ù… ØªÙØ³Ø¬ÙŽÙ‘Ù„ Ø¥Ø¯Ø®Ø§Ù„Ø§Øª ÙˆØ²Ù† Ø¨Ø¹Ø¯.',
      'hi': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤µà¤œà¤¨ à¤ªà¥à¤°à¤µà¤¿à¤·à¥à¤Ÿà¤¿ à¤¦à¤°à¥à¤œ à¤¨à¤¹à¥€à¤‚ à¤•à¥€ à¤—à¤ˆà¥¤',
      'zh': 'å°šæœªè®°å½•ä»»ä½•ä½“é‡æ•°æ®ã€‚',
      'ja': 'ã¾ã ä½“é‡è¨˜éŒ²ãŒã‚ã‚Šã¾ã›ã‚“ã€‚',
      'ko': 'ì•„ì§ ì²´ì¤‘ í•­ëª©ì´ ê¸°ë¡ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.',
      'ru': 'Ð—Ð°Ð¿Ð¸ÑÐ¸ Ð²ÐµÑÐ° ÐµÑ‰Ñ‘ Ð½Ðµ Ð´Ð¾Ð±Ð°Ð²Ð»ÐµÐ½Ñ‹.',
      'tr': 'HenÃ¼z kilo giriÅŸi kaydedilmedi.',
    },
    'Tap \'Log Weight\' below to record your first entry.': {
      'es': 'Toca \'Registrar Peso\' abajo para registrar tu primera entrada.',
      'fr': 'Appuyez sur \'Enregistrer le Poids\' ci-dessous pour votre premiÃ¨re entrÃ©e.',
      'de': 'Tippe auf \'Gewicht erfassen\', um deinen ersten Eintrag zu speichern.',
      'it': 'Tocca \'Registra Peso\' in basso per registrare la tua prima voce.',
      'pt': 'Toque em \'Registrar Peso\' abaixo para registrar sua primeira entrada.',
      'ar': 'Ø§Ø¶ØºØ· Ø¹Ù„Ù‰ \'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„ÙˆØ²Ù†\' Ø£Ø¯Ù†Ø§Ù‡ Ù„ØªØ³Ø¬ÙŠÙ„ Ø£ÙˆÙ„ Ø¥Ø¯Ø®Ø§Ù„.',
      'hi': 'à¤…à¤ªà¤¨à¥€ à¤ªà¤¹à¤²à¥€ à¤ªà¥à¤°à¤µà¤¿à¤·à¥à¤Ÿà¤¿ à¤¦à¤°à¥à¤œ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤¨à¥€à¤šà¥‡ \'à¤µà¤œà¤¨ à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚\' à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚à¥¤',
      'zh': 'ç‚¹å‡»ä¸‹æ–¹\'è®°å½•ä½“é‡\'æ¥è®°å½•æ‚¨çš„ç¬¬ä¸€æ¡æ•°æ®ã€‚',
      'ja': 'æœ€åˆã®ã‚¨ãƒ³ãƒˆãƒªãƒ¼ã‚’è¨˜éŒ²ã™ã‚‹ã«ã¯ä¸‹ã®\'ä½“é‡ã‚’è¨˜éŒ²\'ã‚’ã‚¿ãƒƒãƒ—ã—ã¦ãã ã•ã„ã€‚',
      'ko': 'ì²« ë²ˆì§¸ í•­ëª©ì„ ê¸°ë¡í•˜ë ¤ë©´ ì•„ëž˜ì˜ \'ì²´ì¤‘ ê¸°ë¡\'ì„ íƒ­í•˜ì„¸ìš”.',
      'ru': 'ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ \'Ð—Ð°Ð¿Ð¸ÑÐ°Ñ‚ÑŒ Ð²ÐµÑ\' Ð²Ð½Ð¸Ð·Ñƒ, Ñ‡Ñ‚Ð¾Ð±Ñ‹ Ð´Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ Ð¿ÐµÑ€Ð²ÑƒÑŽ Ð·Ð°Ð¿Ð¸ÑÑŒ.',
      'tr': 'Ä°lk giriÅŸinizi kaydetmek iÃ§in aÅŸaÄŸÄ±daki \'Kilo Kaydet\'e dokunun.',
    },
    // â”€â”€ Health Calculator Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Calculate your BMI, BMR, TDEE and customized daily nutrition targets.': {
      'es': 'Calcula tu IMC, TMB, TDEE y objetivos nutricionales diarios personalizados.',
      'fr': 'Calculez votre IMC, MB, TDEE et vos objectifs nutritionnels journaliers.',
      'de': 'Berechne deinen BMI, BMR, TDEE und individuelle ErnÃ¤hrungsziele.',
      'it': 'Calcola il tuo IMC, BMR, TDEE e obiettivi nutrizionali personalizzati.',
      'pt': 'Calcule seu IMC, TMB, TDEE e metas nutricionais diÃ¡rias personalizadas.',
      'ar': 'Ø§Ø­Ø³Ø¨ Ù…Ø¤Ø´Ø± ÙƒØªÙ„Ø© Ø§Ù„Ø¬Ø³Ù… ÙˆÙ…Ø¹Ø¯Ù„ Ø§Ù„Ø£ÙŠØ¶ Ø§Ù„Ø£Ø³Ø§Ø³ÙŠ ÙˆØ§Ù„Ø¥Ù†ÙØ§Ù‚ Ø§Ù„ÙŠÙˆÙ…ÙŠ ÙˆØ£Ù‡Ø¯Ø§ÙÙƒ Ø§Ù„ØºØ°Ø§Ø¦ÙŠØ©.',
      'hi': 'à¤…à¤ªà¤¨à¤¾ BMI, BMR, TDEE à¤”à¤° à¤•à¤¸à¥à¤Ÿà¤® à¤¦à¥ˆà¤¨à¤¿à¤• à¤ªà¥‹à¤·à¤£ à¤²à¤•à¥à¤·à¥à¤¯ à¤—à¤£à¤¨à¤¾ à¤•à¤°à¥‡à¤‚à¥¤',
      'zh': 'è®¡ç®—æ‚¨çš„BMIã€BMRã€TDEEå’Œä¸ªæ€§åŒ–æ¯æ—¥è¥å…»ç›®æ ‡ã€‚',
      'ja': 'BMIã€BMRã€TDEEã€ã‚«ã‚¹ã‚¿ãƒ æ „é¤Šç›®æ¨™ã‚’è¨ˆç®—ã—ã¾ã™ã€‚',
      'ko': 'BMI, BMR, TDEE ë° ë§žì¶¤í˜• ì¼ì¼ ì˜ì–‘ ëª©í‘œë¥¼ ê³„ì‚°í•˜ì„¸ìš”.',
      'ru': 'Ð Ð°ÑÑÑ‡Ð¸Ñ‚Ð°Ð¹Ñ‚Ðµ Ð˜ÐœÐ¢, BMR, TDEE Ð¸ Ð¸Ð½Ð´Ð¸Ð²Ð¸Ð´ÑƒÐ°Ð»ÑŒÐ½Ñ‹Ðµ Ñ†ÐµÐ»Ð¸ Ð¿Ð¸Ñ‚Ð°Ð½Ð¸Ñ.',
      'tr': 'BMI, BMR, TDEE ve Ã¶zelleÅŸtirilmiÅŸ gÃ¼nlÃ¼k beslenme hedeflerinizi hesaplayÄ±n.',
    },
    'Personal Data': {
      'es': 'Datos Personales',
      'fr': 'DonnÃ©es Personnelles',
      'de': 'PersÃ¶nliche Daten',
      'it': 'Dati Personali',
      'pt': 'Dados Pessoais',
      'ar': 'Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø´Ø®ØµÙŠØ©',
      'hi': 'à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¡à¥‡à¤Ÿà¤¾',
      'zh': 'ä¸ªäººæ•°æ®',
      'ja': 'å€‹äººãƒ‡ãƒ¼ã‚¿',
      'ko': 'ê°œì¸ ë°ì´í„°',
      'ru': 'Ð›Ð¸Ñ‡Ð½Ñ‹Ðµ Ð´Ð°Ð½Ð½Ñ‹Ðµ',
      'tr': 'KiÅŸisel Veriler',
    },
    'Height (cm)': {
      'es': 'Altura (cm)',
      'fr': 'Taille (cm)',
      'de': 'GrÃ¶ÃŸe (cm)',
      'it': 'Altezza (cm)',
      'pt': 'Altura (cm)',
      'ar': 'Ø§Ù„Ø·ÙˆÙ„ (Ø³Ù…)',
      'hi': 'à¤Šà¤‚à¤šà¤¾à¤ˆ (à¤¸à¥‡à¤®à¥€)',
      'zh': 'èº«é«˜ (cm)',
      'ja': 'èº«é•· (cm)',
      'ko': 'ì‹ ìž¥ (cm)',
      'ru': 'Ð Ð¾ÑÑ‚ (ÑÐ¼)',
      'tr': 'Boy (cm)',
    },
    'Weight (kg)': {
      'es': 'Peso (kg)',
      'fr': 'Poids (kg)',
      'de': 'Gewicht (kg)',
      'it': 'Peso (kg)',
      'pt': 'Peso (kg)',
      'ar': 'Ø§Ù„ÙˆØ²Ù† (ÙƒØ¬Ù…)',
      'hi': 'à¤µà¤œà¤¨ (à¤•à¤¿à¤—à¥à¤°à¤¾)',
      'zh': 'ä½“é‡ (kg)',
      'ja': 'ä½“é‡ (kg)',
      'ko': 'ì²´ì¤‘ (kg)',
      'ru': 'Ð’ÐµÑ (ÐºÐ³)',
      'tr': 'AÄŸÄ±rlÄ±k (kg)',
    },
    'Age (yrs)': {
      'es': 'Edad (aÃ±os)',
      'fr': 'Ã‚ge (ans)',
      'de': 'Alter (Jahre)',
      'it': 'EtÃ  (anni)',
      'pt': 'Idade (anos)',
      'ar': 'Ø§Ù„Ø¹Ù…Ø± (Ø³Ù†ÙˆØ§Øª)',
      'hi': 'à¤†à¤¯à¥ (à¤µà¤°à¥à¤·)',
      'zh': 'å¹´é¾„ (å²)',
      'ja': 'å¹´é½¢ (æ­³)',
      'ko': 'ë‚˜ì´ (ì„¸)',
      'ru': 'Ð’Ð¾Ð·Ñ€Ð°ÑÑ‚ (Ð»ÐµÑ‚)',
      'tr': 'YaÅŸ (yÄ±l)',
    },
    'Gender': {
      'es': 'GÃ©nero',
      'fr': 'Genre',
      'de': 'Geschlecht',
      'it': 'Sesso',
      'pt': 'GÃªnero',
      'ar': 'Ø§Ù„Ø¬Ù†Ø³',
      'hi': 'à¤²à¤¿à¤‚à¤—',
      'zh': 'æ€§åˆ«',
      'ja': 'æ€§åˆ¥',
      'ko': 'ì„±ë³„',
      'ru': 'ÐŸÐ¾Ð»',
      'tr': 'Cinsiyet',
    },
    'Activity Level': {
      'es': 'Nivel de Actividad',
      'fr': 'Niveau d\'ActivitÃ©',
      'de': 'AktivitÃ¤tsniveau',
      'it': 'Livello di AttivitÃ ',
      'pt': 'NÃ­vel de Atividade',
      'ar': 'Ù…Ø³ØªÙˆÙ‰ Ø§Ù„Ù†Ø´Ø§Ø·',
      'hi': 'à¤—à¤¤à¤¿à¤µà¤¿à¤§à¤¿ à¤¸à¥à¤¤à¤°',
      'zh': 'æ´»åŠ¨æ°´å¹³',
      'ja': 'æ´»å‹•ãƒ¬ãƒ™ãƒ«',
      'ko': 'í™œë™ ìˆ˜ì¤€',
      'ru': 'Ð£Ñ€Ð¾Ð²ÐµÐ½ÑŒ Ð°ÐºÑ‚Ð¸Ð²Ð½Ð¾ÑÑ‚Ð¸',
      'tr': 'Aktivite Seviyesi',
    },
    'Fitness Goal': {
      'es': 'Objetivo de Fitness',
      'fr': 'Objectif de Forme',
      'de': 'Fitnessziel',
      'it': 'Obiettivo Fitness',
      'pt': 'Meta de Fitness',
      'ar': 'Ù‡Ø¯Ù Ø§Ù„Ù„ÙŠØ§Ù‚Ø©',
      'hi': 'à¤«à¤¿à¤Ÿà¤¨à¥‡à¤¸ à¤²à¤•à¥à¤·à¥à¤¯',
      'zh': 'å¥èº«ç›®æ ‡',
      'ja': 'ãƒ•ã‚£ãƒƒãƒˆãƒã‚¹ç›®æ¨™',
      'ko': 'í”¼íŠ¸ë‹ˆìŠ¤ ëª©í‘œ',
      'ru': 'Ð¦ÐµÐ»ÑŒ Ñ„Ð¸Ñ‚Ð½ÐµÑÐ°',
      'tr': 'Fitness Hedefi',
    },
    'Save & Apply to App Profile': {
      'es': 'Guardar y Aplicar al Perfil',
      'fr': 'Enregistrer et appliquer au profil',
      'de': 'Speichern & Auf Profil anwenden',
      'it': 'Salva e Applica al Profilo',
      'pt': 'Salvar e Aplicar ao Perfil',
      'ar': 'Ø­ÙØ¸ ÙˆØªØ·Ø¨ÙŠÙ‚ Ø¹Ù„Ù‰ Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
      'hi': 'à¤¸à¤¹à¥‡à¤œà¥‡à¤‚ à¤”à¤° à¤ªà¥à¤°à¥‹à¤«à¤¼à¤¾à¤‡à¤² à¤ªà¤° à¤²à¤¾à¤—à¥‚ à¤•à¤°à¥‡à¤‚',
      'zh': 'ä¿å­˜å¹¶åº”ç”¨åˆ°åº”ç”¨é…ç½®æ–‡ä»¶',
      'ja': 'ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«ã«ä¿å­˜ã—ã¦é©ç”¨',
      'ko': 'ì €ìž¥ í›„ ì•± í”„ë¡œí•„ì— ì ìš©',
      'ru': 'Ð¡Ð¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ Ð¸ Ð¿Ñ€Ð¸Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ðº Ð¿Ñ€Ð¾Ñ„Ð¸Ð»ÑŽ',
      'tr': 'Kaydet ve Uygulama Profiline Uygula',
    },
    'Your Calculation Results': {
      'es': 'Tus Resultados de CÃ¡lculo',
      'fr': 'Vos RÃ©sultats de Calcul',
      'de': 'Deine Berechnungsergebnisse',
      'it': 'I Tuoi Risultati di Calcolo',
      'pt': 'Seus Resultados de CÃ¡lculo',
      'ar': 'Ù†ØªØ§Ø¦Ø¬ Ø­Ø³Ø§Ø¨Ùƒ',
      'hi': 'à¤†à¤ªà¤•à¥‡ à¤—à¤£à¤¨à¤¾ à¤ªà¤°à¤¿à¤£à¤¾à¤®',
      'zh': 'æ‚¨çš„è®¡ç®—ç»“æžœ',
      'ja': 'è¨ˆç®—çµæžœ',
      'ko': 'ê³„ì‚° ê²°ê³¼',
      'ru': 'Ð’Ð°ÑˆÐ¸ Ñ€ÐµÐ·ÑƒÐ»ÑŒÑ‚Ð°Ñ‚Ñ‹ Ñ€Ð°ÑÑ‡Ñ‘Ñ‚Ð°',
      'tr': 'Hesaplama SonuÃ§larÄ±nÄ±z',
    },
    'Body Mass Index (BMI)': {
      'es': 'Ãndice de Masa Corporal (IMC)',
      'fr': 'Indice de Masse Corporelle (IMC)',
      'de': 'Body-Mass-Index (BMI)',
      'it': 'Indice di Massa Corporea (IMC)',
      'pt': 'Ãndice de Massa Corporal (IMC)',
      'ar': 'Ù…Ø¤Ø´Ø± ÙƒØªÙ„Ø© Ø§Ù„Ø¬Ø³Ù… (BMI)',
      'hi': 'à¤¬à¥‰à¤¡à¥€ à¤®à¤¾à¤¸ à¤‡à¤‚à¤¡à¥‡à¤•à¥à¤¸ (BMI)',
      'zh': 'èº«ä½“è´¨é‡æŒ‡æ•° (BMI)',
      'ja': 'ãƒœãƒ‡ã‚£ãƒžã‚¹æŒ‡æ•° (BMI)',
      'ko': 'ì²´ì§ˆëŸ‰ì§€ìˆ˜ (BMI)',
      'ru': 'Ð˜Ð½Ð´ÐµÐºÑ Ð¼Ð°ÑÑÑ‹ Ñ‚ÐµÐ»Ð° (Ð˜ÐœÐ¢)',
      'tr': 'VÃ¼cut Kitle Ä°ndeksi (VKÄ°)',
    },
    'Height-to-weight ratio': {
      'es': 'RelaciÃ³n altura-peso',
      'fr': 'Rapport taille-poids',
      'de': 'GrÃ¶ÃŸe-zu-Gewicht-VerhÃ¤ltnis',
      'it': 'Rapporto altezza-peso',
      'pt': 'RelaÃ§Ã£o altura-peso',
      'ar': 'Ù†Ø³Ø¨Ø© Ø§Ù„Ø·ÙˆÙ„ Ø¥Ù„Ù‰ Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤Šà¤‚à¤šà¤¾à¤ˆ-à¤µà¤œà¤¨ à¤…à¤¨à¥à¤ªà¤¾à¤¤',
      'zh': 'èº«é«˜ä½“é‡æ¯”',
      'ja': 'èº«é•·ä½“é‡æ¯”',
      'ko': 'í‚¤ ëŒ€ ì²´ì¤‘ ë¹„ìœ¨',
      'ru': 'Ð¡Ð¾Ð¾Ñ‚Ð½Ð¾ÑˆÐµÐ½Ð¸Ðµ Ñ€Ð¾ÑÑ‚Ð° Ð¸ Ð²ÐµÑÐ°',
      'tr': 'Boy-kilo oranÄ±',
    },
    'Basal Metabolic Rate': {
      'es': 'Tasa MetabÃ³lica Basal',
      'fr': 'MÃ©tabolisme de Base',
      'de': 'Grundumsatz',
      'it': 'Metabolismo Basale',
      'pt': 'Taxa MetabÃ³lica Basal',
      'ar': 'Ù…Ø¹Ø¯Ù„ Ø§Ù„Ø£ÙŠØ¶ Ø§Ù„Ø£Ø³Ø§Ø³ÙŠ',
      'hi': 'à¤¬à¥‡à¤¸à¤² à¤®à¥‡à¤Ÿà¤¾à¤¬à¥‹à¤²à¤¿à¤• à¤°à¥‡à¤Ÿ',
      'zh': 'åŸºç¡€ä»£è°¢çŽ‡',
      'ja': 'åŸºç¤Žä»£è¬é‡',
      'ko': 'ê¸°ì´ˆ ëŒ€ì‚¬ìœ¨',
      'ru': 'Ð‘Ð°Ð·Ð°Ð»ÑŒÐ½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð°Ð±Ð¾Ð»Ð¸Ð·Ð¼',
      'tr': 'Bazal Metabolizma HÄ±zÄ±',
    },
    'Maintenance Energy': {
      'es': 'EnergÃ­a de Mantenimiento',
      'fr': 'Ã‰nergie de Maintenance',
      'de': 'Erhaltungsenergie',
      'it': 'Energia di Mantenimento',
      'pt': 'Energia de ManutenÃ§Ã£o',
      'ar': 'Ø·Ø§Ù‚Ø© Ø§Ù„ØµÙŠØ§Ù†Ø©',
      'hi': 'à¤°à¤–à¤°à¤–à¤¾à¤µ à¤Šà¤°à¥à¤œà¤¾',
      'zh': 'ç»´æŒèƒ½é‡',
      'ja': 'ç¶­æŒã‚¨ãƒãƒ«ã‚®ãƒ¼',
      'ko': 'ìœ ì§€ ì—ë„ˆì§€',
      'ru': 'ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶Ð¸Ð²Ð°ÑŽÑ‰Ð°Ñ ÑÐ½ÐµÑ€Ð³Ð¸Ñ',
      'tr': 'BakÄ±m Enerjisi',
    },
    'Target Daily Calories': {
      'es': 'CalorÃ­as Diarias Objetivo',
      'fr': 'Calories Quotidiennes Cibles',
      'de': 'TÃ¤gliche Zielkalorien',
      'it': 'Calorie Giornaliere Target',
      'pt': 'Calorias DiÃ¡rias Alvo',
      'ar': 'Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ© Ø§Ù„ÙŠÙˆÙ…ÙŠØ© Ø§Ù„Ù…Ø³ØªÙ‡Ø¯ÙØ©',
      'hi': 'à¤²à¤•à¥à¤·à¤¿à¤¤ à¤¦à¥ˆà¤¨à¤¿à¤• à¤•à¥ˆà¤²à¥‹à¤°à¥€',
      'zh': 'ç›®æ ‡æ¯æ—¥å¡è·¯é‡Œ',
      'ja': 'ç›®æ¨™1æ—¥ã‚«ãƒ­ãƒªãƒ¼',
      'ko': 'ëª©í‘œ ì¼ì¼ ì¹¼ë¡œë¦¬',
      'ru': 'Ð¦ÐµÐ»ÐµÐ²Ñ‹Ðµ ÑÑƒÑ‚Ð¾Ñ‡Ð½Ñ‹Ðµ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¸',
      'tr': 'Hedef GÃ¼nlÃ¼k Kalori',
    },
    'Recommended Macros Breakdown': {
      'es': 'Desglose de Macros Recomendados',
      'fr': 'RÃ©partition des Macros RecommandÃ©s',
      'de': 'Empfohlene Makro-Aufteilung',
      'it': 'Ripartizione Macros Consigliati',
      'pt': 'DivisÃ£o de Macros Recomendados',
      'ar': 'ØªÙˆØ²ÙŠØ¹ Ø§Ù„Ø¹Ù†Ø§ØµØ± Ø§Ù„ØºØ°Ø§Ø¦ÙŠØ© Ø§Ù„ÙƒØ¨Ø±Ù‰ Ø§Ù„Ù…ÙˆØµÙ‰ Ø¨Ù‡Ø§',
      'hi': 'à¤…à¤¨à¥à¤¶à¤‚à¤¸à¤¿à¤¤ à¤®à¥ˆà¤•à¥à¤°à¥‹ à¤µà¤¿à¤­à¤¾à¤œà¤¨',
      'zh': 'æŽ¨èå®é‡è¥å…»ç´ åˆ†é…',
      'ja': 'æŽ¨å¥¨ãƒžã‚¯ãƒ­å†…è¨³',
      'ko': 'ê¶Œìž¥ ë§¤í¬ë¡œ ë¶„ë¥˜',
      'ru': 'Ð ÐµÐºÐ¾Ð¼ÐµÐ½Ð´ÑƒÐµÐ¼Ð¾Ðµ Ñ€Ð°ÑÐ¿Ñ€ÐµÐ´ÐµÐ»ÐµÐ½Ð¸Ðµ Ð¼Ð°ÐºÑ€Ð¾ÑÐ¾Ð²',
      'tr': 'Ã–nerilen Makro DaÄŸÄ±lÄ±mÄ±',
    },
    'Sedentary': {
      'es': 'Sedentario',
      'fr': 'SÃ©dentaire',
      'de': 'Sitzend',
      'it': 'Sedentario',
      'pt': 'SedentÃ¡rio',
      'ar': 'Ù…Ø³ØªÙ‚Ø±',
      'hi': 'à¤¨à¤¿à¤·à¥à¤•à¥à¤°à¤¿à¤¯',
      'zh': 'ä¹…å',
      'ja': 'åº§ã‚Šä»•äº‹',
      'ko': 'ì¢Œì‹ ìƒí™œ',
      'ru': 'ÐœÐ°Ð»Ð¾Ð¿Ð¾Ð´Ð²Ð¸Ð¶Ð½Ñ‹Ð¹',
      'tr': 'Hareketsiz',
    },
    'Lightly Active': {
      'es': 'Ligeramente Activo',
      'fr': 'LÃ©gÃ¨rement Actif',
      'de': 'Leicht Aktiv',
      'it': 'Leggermente Attivo',
      'pt': 'Levemente Ativo',
      'ar': 'Ù†Ø´Ø· Ù‚Ù„ÙŠÙ„Ø§Ù‹',
      'hi': 'à¤¥à¥‹à¤¡à¤¼à¤¾ à¤¸à¤•à¥à¤°à¤¿à¤¯',
      'zh': 'è½»åº¦æ´»è·ƒ',
      'ja': 'è»½ã„æ´»å‹•',
      'ko': 'ì•½ê°„ í™œë™ì ',
      'ru': 'Ð¡Ð»ÐµÐ³ÐºÐ° Ð°ÐºÑ‚Ð¸Ð²Ð½Ñ‹Ð¹',
      'tr': 'Hafif Aktif',
    },
    'Moderately Active': {
      'es': 'Moderadamente Activo',
      'fr': 'ModÃ©rÃ©ment Actif',
      'de': 'MÃ¤ÃŸig Aktiv',
      'it': 'Moderatamente Attivo',
      'pt': 'Moderadamente Ativo',
      'ar': 'Ù†Ø´Ø· Ø¨Ø´ÙƒÙ„ Ù…Ø¹ØªØ¯Ù„',
      'hi': 'à¤®à¤§à¥à¤¯à¤® à¤¸à¤•à¥à¤°à¤¿à¤¯',
      'zh': 'é€‚åº¦æ´»è·ƒ',
      'ja': 'é©åº¦ãªæ´»å‹•',
      'ko': 'ë³´í†µ í™œë™ì ',
      'ru': 'Ð£Ð¼ÐµÑ€ÐµÐ½Ð½Ð¾ Ð°ÐºÑ‚Ð¸Ð²Ð½Ñ‹Ð¹',
      'tr': 'Orta Derecede Aktif',
    },
    'Very Active': {
      'es': 'Muy Activo',
      'fr': 'TrÃ¨s Actif',
      'de': 'Sehr Aktiv',
      'it': 'Molto Attivo',
      'pt': 'Muito Ativo',
      'ar': 'Ù†Ø´Ø· Ø¬Ø¯Ø§Ù‹',
      'hi': 'à¤¬à¤¹à¥à¤¤ à¤¸à¤•à¥à¤°à¤¿à¤¯',
      'zh': 'éžå¸¸æ´»è·ƒ',
      'ja': 'éžå¸¸ã«æ´»å‹•çš„',
      'ko': 'ë§¤ìš° í™œë™ì ',
      'ru': 'ÐžÑ‡ÐµÐ½ÑŒ Ð°ÐºÑ‚Ð¸Ð²Ð½Ñ‹Ð¹',
      'tr': 'Ã‡ok Aktif',
    },
    'Lose Weight': {
      'es': 'Perder Peso',
      'fr': 'Perdre du Poids',
      'de': 'Gewicht verlieren',
      'it': 'Perdere Peso',
      'pt': 'Perder Peso',
      'ar': 'ÙÙ‚Ø¯Ø§Ù† Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤˜à¤Ÿà¤¾à¤¨à¤¾',
      'zh': 'å‡é‡',
      'ja': 'ä½“é‡ã‚’æ¸›ã‚‰ã™',
      'ko': 'ì²´ì¤‘ ê°ëŸ‰',
      'ru': 'Ð¡Ð±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ Ð²ÐµÑ',
      'tr': 'Kilo Vermek',
    },
    'Maintain Weight': {
      'es': 'Mantener Peso',
      'fr': 'Maintenir le Poids',
      'de': 'Gewicht halten',
      'it': 'Mantenere il Peso',
      'pt': 'Manter o Peso',
      'ar': 'Ø§Ù„Ø­ÙØ§Ø¸ Ø¹Ù„Ù‰ Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤¬à¤¨à¤¾à¤ à¤°à¤–à¤¨à¤¾',
      'zh': 'ä¿æŒä½“é‡',
      'ja': 'ä½“é‡ã‚’ç¶­æŒã™ã‚‹',
      'ko': 'ì²´ì¤‘ ìœ ì§€',
      'ru': 'ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶Ð¸Ð²Ð°Ñ‚ÑŒ Ð²ÐµÑ',
      'tr': 'Kiloyu Korumak',
    },
    'Gain Weight': {
      'es': 'Ganar Peso',
      'fr': 'Prendre du Poids',
      'de': 'Gewicht zunehmen',
      'it': 'Aumentare di Peso',
      'pt': 'Ganhar Peso',
      'ar': 'Ø²ÙŠØ§Ø¯Ø© Ø§Ù„ÙˆØ²Ù†',
      'hi': 'à¤µà¤œà¤¨ à¤¬à¤¢à¤¼à¤¾à¤¨à¤¾',
      'zh': 'å¢žé‡',
      'ja': 'ä½“é‡ã‚’å¢—ã‚„ã™',
      'ko': 'ì²´ì¤‘ ì¦ê°€',
      'ru': 'ÐÐ°Ð±Ñ€Ð°Ñ‚ÑŒ Ð²ÐµÑ',
      'tr': 'Kilo Almak',
    },
    'Male': {
      'es': 'Masculino',
      'fr': 'Homme',
      'de': 'MÃ¤nnlich',
      'it': 'Maschio',
      'pt': 'Masculino',
      'ar': 'Ø°ÙƒØ±',
      'hi': 'à¤ªà¥à¤°à¥à¤·',
      'zh': 'ç”·æ€§',
      'ja': 'ç”·æ€§',
      'ko': 'ë‚¨ì„±',
      'ru': 'ÐœÑƒÐ¶ÑÐºÐ¾Ð¹',
      'tr': 'Erkek',
    },
    'Female': {
      'es': 'Femenino',
      'fr': 'Femme',
      'de': 'Weiblich',
      'it': 'Femmina',
      'pt': 'Feminino',
      'ar': 'Ø£Ù†Ø«Ù‰',
      'hi': 'à¤®à¤¹à¤¿à¤²à¤¾',
      'zh': 'å¥³æ€§',
      'ja': 'å¥³æ€§',
      'ko': 'ì—¬ì„±',
      'ru': 'Ð–ÐµÐ½ÑÐºÐ¸Ð¹',
      'tr': 'KadÄ±n',
    },
    'Other': {
      'es': 'Otro',
      'fr': 'Autre',
      'de': 'Andere',
      'it': 'Altro',
      'pt': 'Outro',
      'ar': 'Ø¢Ø®Ø±',
      'hi': 'à¤…à¤¨à¥à¤¯',
      'zh': 'å…¶ä»–',
      'ja': 'ãã®ä»–',
      'ko': 'ê¸°íƒ€',
      'ru': 'Ð”Ñ€ÑƒÐ³Ð¾Ðµ',
      'tr': 'DiÄŸer',
    },
    'Food Name': {
      'es': 'Nombre del Alimento',
      'fr': 'Nom de l\'Aliment',
      'de': 'Lebensmittelname',
      'it': 'Nome dell\'Alimento',
      'pt': 'Nome do Alimento',
      'ar': 'Ø§Ø³Ù… Ø§Ù„Ø·Ø¹Ø§Ù…',
      'hi': 'à¤–à¤¾à¤¦à¥à¤¯ à¤¨à¤¾à¤®',
      'zh': 'é£Ÿç‰©åç§°',
      'ja': 'é£Ÿå“å',
      'ko': 'ìŒì‹ ì´ë¦„',
      'ru': 'ÐÐ°Ð·Ð²Ð°Ð½Ð¸Ðµ Ð±Ð»ÑŽÐ´Ð°',
      'tr': 'Yiyecek AdÄ±',
    },
    'Calories': {
      'es': 'CalorÃ­as',
      'fr': 'Calories',
      'de': 'Kalorien',
      'it': 'Calorie',
      'pt': 'Calorias',
      'ar': 'Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ©',
      'hi': 'à¤•à¥ˆà¤²à¥‹à¤°à¥€',
      'zh': 'å¡è·¯é‡Œ',
      'ja': 'ã‚«ãƒ­ãƒªãƒ¼',
      'ko': 'ì¹¼ë¡œë¦¬',
      'ru': 'ÐšÐ°Ð»Ð¾Ñ€Ð¸Ð¸',
      'tr': 'Kalori',
    },
    'Protein (g)': {
      'es': 'ProteÃ­na (g)',
      'fr': 'ProtÃ©ines (g)',
      'de': 'Protein (g)',
      'it': 'Proteine (g)',
      'pt': 'ProteÃ­na (g)',
      'ar': 'Ø¨Ø±ÙˆØªÙŠÙ† (Øº)',
      'hi': 'à¤ªà¥à¤°à¥‹à¤Ÿà¥€à¤¨ (à¤—à¥à¤°à¤¾)',
      'zh': 'è›‹ç™½è´¨ (g)',
      'ja': 'ã‚¿ãƒ³ãƒ‘ã‚¯è³ª (g)',
      'ko': 'ë‹¨ë°±ì§ˆ (g)',
      'ru': 'Ð‘ÐµÐ»Ð¾Ðº (Ð³)',
      'tr': 'Protein (g)',
    },
    'Carbs (g)': {
      'es': 'Carbohidratos (g)',
      'fr': 'Glucides (g)',
      'de': 'Kohlenhydrate (g)',
      'it': 'Carboidrati (g)',
      'pt': 'Carboidratos (g)',
      'ar': 'Ø§Ù„ÙƒØ±Ø¨ÙˆÙ‡ÙŠØ¯Ø±Ø§Øª (Øº)',
      'hi': 'à¤•à¤¾à¤°à¥à¤¬à¥‹à¤¹à¤¾à¤‡à¤¡à¥à¤°à¥‡à¤Ÿ (à¤—à¥à¤°à¤¾)',
      'zh': 'ç¢³æ°´åŒ–åˆç‰© (g)',
      'ja': 'ç‚­æ°´åŒ–ç‰© (g)',
      'ko': 'íƒ„ìˆ˜í™”ë¬¼ (g)',
      'ru': 'Ð£Ð³Ð»ÐµÐ²Ð¾Ð´Ñ‹ (Ð³)',
      'tr': 'Karbonhidrat (g)',
    },
    'Fat (g)': {
      'es': 'Grasa (g)',
      'fr': 'Graisses (g)',
      'de': 'Fett (g)',
      'it': 'Grassi (g)',
      'pt': 'Gordura (g)',
      'ar': 'Ø§Ù„Ø¯Ù‡ÙˆÙ† (Øº)',
      'hi': 'à¤µà¤¸à¤¾ (à¤—à¥à¤°à¤¾)',
      'zh': 'è„‚è‚ª (g)',
      'ja': 'è„‚è³ª (g)',
      'ko': 'ì§€ë°© (g)',
      'ru': 'Ð–Ð¸Ñ€Ñ‹ (Ð³)',
      'tr': 'YaÄŸ (g)',
    },
    'Quantity': {
      'es': 'Cantidad',
      'fr': 'QuantitÃ©',
      'de': 'Menge',
      'it': 'QuantitÃ ',
      'pt': 'Quantidade',
      'ar': 'Ø§Ù„ÙƒÙ…ÙŠØ©',
      'hi': 'à¤®à¤¾à¤¤à¥à¤°à¤¾',
      'zh': 'æ•°é‡',
      'ja': 'é‡',
      'ko': 'ìˆ˜ëŸ‰',
      'ru': 'ÐšÐ¾Ð»Ð¸Ñ‡ÐµÑÑ‚Ð²Ð¾',
      'tr': 'Miktar',
    },
    'Please fill all fields': {
      'es': 'Por favor completa todos los campos',
      'fr': 'Veuillez remplir tous les champs',
      'de': 'Bitte alle Felder ausfÃ¼llen',
      'it': 'Si prega di compilare tutti i campi',
      'pt': 'Por favor preencha todos os campos',
      'ar': 'ÙŠØ±Ø¬Ù‰ Ù…Ù„Ø¡ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ„',
      'hi': 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤¸à¤­à¥€ à¤«à¤¼à¥€à¤²à¥à¤¡ à¤­à¤°à¥‡à¤‚',
      'zh': 'è¯·å¡«å†™æ‰€æœ‰å­—æ®µ',
      'ja': 'ã™ã¹ã¦ã®ãƒ•ã‚£ãƒ¼ãƒ«ãƒ‰ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„',
      'ko': 'ëª¨ë“  í•„ë“œë¥¼ ìž…ë ¥í•´ì£¼ì„¸ìš”',
      'ru': 'ÐŸÐ¾Ð¶Ð°Ð»ÑƒÐ¹ÑÑ‚Ð°, Ð·Ð°Ð¿Ð¾Ð»Ð½Ð¸Ñ‚Ðµ Ð²ÑÐµ Ð¿Ð¾Ð»Ñ',
      'tr': 'LÃ¼tfen tÃ¼m alanlarÄ± doldurun',
    },
    'Confirm AI Meal': {
      'es': 'Confirmar Comida IA',
      'fr': 'Confirmer le Repas IA',
      'de': 'KI-Mahlzeit bestÃ¤tigen',
      'it': 'Conferma Pasto IA',
      'pt': 'Confirmar RefeiÃ§Ã£o IA',
      'ar': 'ØªØ£ÙƒÙŠØ¯ ÙˆØ¬Ø¨Ø© Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ',
      'hi': 'AI à¤­à¥‹à¤œà¤¨ à¤•à¥€ à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤•à¤°à¥‡à¤‚',
      'zh': 'ç¡®è®¤AIé¤é£Ÿ',
      'ja': 'AIé£Ÿäº‹ã‚’ç¢ºèª',
      'ko': 'AI ì‹ì‚¬ í™•ì¸',
      'ru': 'ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ Ð±Ð»ÑŽÐ´Ð¾ Ð¾Ñ‚ Ð˜Ð˜',
      'tr': 'AI Ã–ÄŸÃ¼nÃ¼nÃ¼ Onayla',
    },
    // â”€â”€ Settings Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Settings': {
      'es': 'ConfiguraciÃ³n',
      'fr': 'ParamÃ¨tres',
      'de': 'Einstellungen',
      'it': 'Impostazioni',
      'pt': 'ConfiguraÃ§Ãµes',
      'ar': 'Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª',
      'hi': 'à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸',
      'zh': 'è®¾ç½®',
      'ja': 'è¨­å®š',
      'ko': 'ì„¤ì •',
      'ru': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸',
      'tr': 'Ayarlar',
    },
    'App Settings': {
      'es': 'ConfiguraciÃ³n de la AplicaciÃ³n',
      'fr': 'ParamÃ¨tres de l\'Application',
      'de': 'App-Einstellungen',
      'it': 'Impostazioni App',
      'pt': 'ConfiguraÃ§Ãµes do App',
      'ar': 'Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
      'hi': 'à¤à¤ª à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸',
      'zh': 'åº”ç”¨è®¾ç½®',
      'ja': 'ã‚¢ãƒ—ãƒªè¨­å®š',
      'ko': 'ì•± ì„¤ì •',
      'ru': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ñ',
      'tr': 'Uygulama AyarlarÄ±',
    },
    'Personalize your experience, privacy, and notifications.': {
      'es': 'Personaliza tu experiencia, privacidad y notificaciones.',
      'fr': 'Personnalisez votre expÃ©rience, confidentialitÃ© et notifications.',
      'de': 'Personalisiere dein Erlebnis, Datenschutz und Benachrichtigungen.',
      'it': 'Personalizza la tua esperienza, privacy e notifiche.',
      'pt': 'Personalize sua experiÃªncia, privacidade e notificaÃ§Ãµes.',
      'ar': 'Ø®ØµØµ ØªØ¬Ø±Ø¨ØªÙƒ ÙˆØ®ØµÙˆØµÙŠØªÙƒ ÙˆØ¥Ø´Ø¹Ø§Ø±Ø§ØªÙƒ.',
      'hi': 'à¤…à¤ªà¤¨à¤¾ à¤…à¤¨à¥à¤­à¤µ, à¤—à¥‹à¤ªà¤¨à¥€à¤¯à¤¤à¤¾ à¤”à¤° à¤¸à¥‚à¤šà¤¨à¤¾à¤à¤‚ à¤•à¤¸à¥à¤Ÿà¤®à¤¾à¤‡à¤œà¤¼ à¤•à¤°à¥‡à¤‚à¥¤',
      'zh': 'ä¸ªæ€§åŒ–æ‚¨çš„ä½“éªŒã€éšç§å’Œé€šçŸ¥ã€‚',
      'ja': 'ä½“é¨“ã€ãƒ—ãƒ©ã‚¤ãƒã‚·ãƒ¼ã€é€šçŸ¥ã‚’ã‚«ã‚¹ã‚¿ãƒžã‚¤ã‚ºã€‚',
      'ko': 'ê²½í—˜, ê°œì¸ ì •ë³´ ë³´í˜¸ ë° ì•Œë¦¼ì„ ë§žì¶¤ ì„¤ì •í•˜ì„¸ìš”.',
      'ru': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹Ñ‚Ðµ Ð¸Ð½Ñ‚ÐµÑ€Ñ„ÐµÐ¹Ñ, ÐºÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ Ð¸ ÑƒÐ²ÐµÐ´Ð¾Ð¼Ð»ÐµÐ½Ð¸Ñ.',
      'tr': 'Deneyiminizi, gizliliÄŸinizi ve bildirimlerinizi kiÅŸiselleÅŸtirin.',
    },
    'Notifications': {
      'es': 'Notificaciones',
      'fr': 'Notifications',
      'de': 'Benachrichtigungen',
      'it': 'Notifiche',
      'pt': 'NotificaÃ§Ãµes',
      'ar': 'Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',
      'hi': 'à¤¸à¥‚à¤šà¤¨à¤¾à¤à¤‚',
      'zh': 'é€šçŸ¥',
      'ja': 'é€šçŸ¥',
      'ko': 'ì•Œë¦¼',
      'ru': 'Ð£Ð²ÐµÐ´Ð¾Ð¼Ð»ÐµÐ½Ð¸Ñ',
      'tr': 'Bildirimler',
    },
    'Appearance': {
      'es': 'Apariencia',
      'fr': 'Apparence',
      'de': 'Erscheinungsbild',
      'it': 'Aspetto',
      'pt': 'AparÃªncia',
      'ar': 'Ø§Ù„Ù…Ø¸Ù‡Ø±',
      'hi': 'à¤°à¥‚à¤ª',
      'zh': 'å¤–è§‚',
      'ja': 'å¤–è¦³',
      'ko': 'ì™¸ê´€',
      'ru': 'Ð’Ð½ÐµÑˆÐ½Ð¸Ð¹ Ð²Ð¸Ð´',
      'tr': 'GÃ¶rÃ¼nÃ¼m',
    },
    'Security': {
      'es': 'Seguridad',
      'fr': 'SÃ©curitÃ©',
      'de': 'Sicherheit',
      'it': 'Sicurezza',
      'pt': 'SeguranÃ§a',
      'ar': 'Ø§Ù„Ø£Ù…Ø§Ù†',
      'hi': 'à¤¸à¥à¤°à¤•à¥à¤·à¤¾',
      'zh': 'å®‰å…¨',
      'ja': 'ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£',
      'ko': 'ë³´ì•ˆ',
      'ru': 'Ð‘ÐµÐ·Ð¾Ð¿Ð°ÑÐ½Ð¾ÑÑ‚ÑŒ',
      'tr': 'GÃ¼venlik',
    },
    'Support': {
      'es': 'Soporte',
      'fr': 'Support',
      'de': 'Support',
      'it': 'Supporto',
      'pt': 'Suporte',
      'ar': 'Ø§Ù„Ø¯Ø¹Ù…',
      'hi': 'à¤¸à¤®à¤°à¥à¤¥à¤¨',
      'zh': 'æ”¯æŒ',
      'ja': 'ã‚µãƒãƒ¼ãƒˆ',
      'ko': 'ì§€ì›',
      'ru': 'ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ°',
      'tr': 'Destek',
    },
    'Daily reminders': {
      'es': 'Recordatorios diarios',
      'fr': 'Rappels quotidiens',
      'de': 'TÃ¤gliche Erinnerungen',
      'it': 'Promemoria giornalieri',
      'pt': 'Lembretes diÃ¡rios',
      'ar': 'ØªØ°ÙƒÙŠØ±Ø§Øª ÙŠÙˆÙ…ÙŠØ©',
      'hi': 'à¤¦à¥ˆà¤¨à¤¿à¤• à¤…à¤¨à¥à¤¸à¥à¤®à¤¾à¤°à¤•',
      'zh': 'æ¯æ—¥æé†’',
      'ja': 'æ¯Žæ—¥ã®ãƒªãƒžã‚¤ãƒ³ãƒ€ãƒ¼',
      'ko': 'ë§¤ì¼ ì•Œë¦¼',
      'ru': 'Ð•Ð¶ÐµÐ´Ð½ÐµÐ²Ð½Ñ‹Ðµ Ð½Ð°Ð¿Ð¾Ð¼Ð¸Ð½Ð°Ð½Ð¸Ñ',
      'tr': 'GÃ¼nlÃ¼k hatÄ±rlatmalar',
    },
    'Receive reminders for water and meal goals': {
      'es': 'Recibe recordatorios para metas de agua y comidas',
      'fr': 'Recevez des rappels pour vos objectifs d\'eau et de repas',
      'de': 'Erhalte Erinnerungen fÃ¼r Wasser- und Mahlzeitziele',
      'it': 'Ricevi promemoria per obiettivi idrici e pasti',
      'pt': 'Receba lembretes para metas de Ã¡gua e refeiÃ§Ãµes',
      'ar': 'Ø§Ø­ØµÙ„ Ø¹Ù„Ù‰ ØªØ°ÙƒÙŠØ±Ø§Øª Ù„Ø£Ù‡Ø¯Ø§Ù Ø§Ù„Ù…Ø§Ø¡ ÙˆØ§Ù„ÙˆØ¬Ø¨Ø§Øª',
      'hi': 'à¤ªà¤¾à¤¨à¥€ à¤”à¤° à¤­à¥‹à¤œà¤¨ à¤²à¤•à¥à¤·à¥à¤¯à¥‹à¤‚ à¤•à¥‡ à¤²à¤¿à¤ à¤…à¤¨à¥à¤¸à¥à¤®à¤¾à¤°à¤• à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤•à¤°à¥‡à¤‚',
      'zh': 'èŽ·å–æ°´å’Œé¤é£Ÿç›®æ ‡çš„æé†’',
      'ja': 'æ°´åˆ†ã¨é£Ÿäº‹ç›®æ¨™ã®ãƒªãƒžã‚¤ãƒ³ãƒ€ãƒ¼ã‚’å—ã‘å–ã‚‹',
      'ko': 'ë¬¼ê³¼ ì‹ì‚¬ ëª©í‘œì— ëŒ€í•œ ì•Œë¦¼ ë°›ê¸°',
      'ru': 'ÐŸÐ¾Ð»ÑƒÑ‡Ð°Ð¹Ñ‚Ðµ Ð½Ð°Ð¿Ð¾Ð¼Ð¸Ð½Ð°Ð½Ð¸Ñ Ð¾ Ñ†ÐµÐ»ÑÑ… Ð¿Ð¾ Ð²Ð¾Ð´Ðµ Ð¸ Ð¿Ð¸Ñ‚Ð°Ð½Ð¸ÑŽ',
      'tr': 'Su ve Ã¶ÄŸÃ¼n hedefleri iÃ§in hatÄ±rlatmalar alÄ±n',
    },
    'Goal alerts': {
      'es': 'Alertas de objetivos',
      'fr': 'Alertes d\'objectifs',
      'de': 'Zielbenachrichtigungen',
      'it': 'Avvisi sugli obiettivi',
      'pt': 'Alertas de metas',
      'ar': 'ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø£Ù‡Ø¯Ø§Ù',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯ à¤…à¤²à¤°à¥à¤Ÿ',
      'zh': 'ç›®æ ‡æé†’',
      'ja': 'ç›®æ¨™ã‚¢ãƒ©ãƒ¼ãƒˆ',
      'ko': 'ëª©í‘œ ì•Œë¦¼',
      'ru': 'ÐžÐ¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ Ð¾ Ñ†ÐµÐ»ÑÑ…',
      'tr': 'Hedef uyarÄ±larÄ±',
    },
    'Get notified when you hit your daily targets': {
      'es': 'Recibe notificaciones cuando alcances tus metas diarias',
      'fr': 'Soyez notifiÃ© lorsque vous atteignez vos objectifs journaliers',
      'de': 'Erhalte Benachrichtigungen beim Erreichen deiner Tagesziele',
      'it': 'Ricevi notifiche quando raggiungi i tuoi obiettivi giornalieri',
      'pt': 'Seja notificado quando atingir suas metas diÃ¡rias',
      'ar': 'Ø§Ø­ØµÙ„ Ø¹Ù„Ù‰ Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ ØªØ­Ù‚ÙŠÙ‚ Ø£Ù‡Ø¯Ø§ÙÙƒ Ø§Ù„ÙŠÙˆÙ…ÙŠØ©',
      'hi': 'à¤œà¤¬ à¤†à¤ª à¤…à¤ªà¤¨à¥‡ à¤¦à¥ˆà¤¨à¤¿à¤• à¤²à¤•à¥à¤·à¥à¤¯ à¤ªà¥‚à¤°à¥‡ à¤•à¤°à¥‡à¤‚ à¤¤à¥‹ à¤¸à¥‚à¤šà¤¨à¤¾ à¤ªà¤¾à¤à¤‚',
      'zh': 'è¾¾åˆ°æ¯æ—¥ç›®æ ‡æ—¶èŽ·å¾—é€šçŸ¥',
      'ja': '1æ—¥ã®ç›®æ¨™ã‚’é”æˆã—ãŸã¨ãã«é€šçŸ¥ã‚’å—ã‘å–ã‚‹',
      'ko': 'ì¼ì¼ ëª©í‘œ ë‹¬ì„± ì‹œ ì•Œë¦¼ ë°›ê¸°',
      'ru': 'ÐŸÐ¾Ð»ÑƒÑ‡Ð°Ð¹Ñ‚Ðµ ÑƒÐ²ÐµÐ´Ð¾Ð¼Ð»ÐµÐ½Ð¸Ñ Ð¿Ñ€Ð¸ Ð´Ð¾ÑÑ‚Ð¸Ð¶ÐµÐ½Ð¸Ð¸ Ð´Ð½ÐµÐ²Ð½Ñ‹Ñ… Ñ†ÐµÐ»ÐµÐ¹',
      'tr': 'GÃ¼nlÃ¼k hedeflerinize ulaÅŸtÄ±ÄŸÄ±nÄ±zda bildirim alÄ±n',
    },
    'App theme': {
      'es': 'Tema de la app',
      'fr': 'ThÃ¨me de l\'app',
      'de': 'App-Design',
      'it': 'Tema app',
      'pt': 'Tema do app',
      'ar': 'Ù…Ø¸Ù‡Ø± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
      'hi': 'à¤à¤ª à¤¥à¥€à¤®',
      'zh': 'åº”ç”¨ä¸»é¢˜',
      'ja': 'ã‚¢ãƒ—ãƒªãƒ†ãƒ¼ãƒž',
      'ko': 'ì•± í…Œë§ˆ',
      'ru': 'Ð¢ÐµÐ¼Ð° Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ñ',
      'tr': 'Uygulama temasÄ±',
    },
    'Light mode': {
      'es': 'Modo claro',
      'fr': 'Mode clair',
      'de': 'Hellmodus',
      'it': 'ModalitÃ  chiara',
      'pt': 'Modo claro',
      'ar': 'Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„ÙØ§ØªØ­',
      'hi': 'à¤²à¤¾à¤‡à¤Ÿ à¤®à¥‹à¤¡',
      'zh': 'æµ…è‰²æ¨¡å¼',
      'ja': 'ãƒ©ã‚¤ãƒˆãƒ¢ãƒ¼ãƒ‰',
      'ko': 'ë¼ì´íŠ¸ ëª¨ë“œ',
      'ru': 'Ð¡Ð²ÐµÑ‚Ð»Ð°Ñ Ñ‚ÐµÐ¼Ð°',
      'tr': 'AÃ§Ä±k mod',
    },
    'Dark mode': {
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'de': 'Dunkelmodus',
      'it': 'ModalitÃ  scura',
      'pt': 'Modo escuro',
      'ar': 'Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„Ø¯Ø§ÙƒÙ†',
      'hi': 'à¤¡à¤¾à¤°à¥à¤• à¤®à¥‹à¤¡',
      'zh': 'æ·±è‰²æ¨¡å¼',
      'ja': 'ãƒ€ãƒ¼ã‚¯ãƒ¢ãƒ¼ãƒ‰',
      'ko': 'ë‹¤í¬ ëª¨ë“œ',
      'ru': 'Ð¢Ñ‘Ð¼Ð½Ð°Ñ Ñ‚ÐµÐ¼Ð°',
      'tr': 'KaranlÄ±k mod',
    },
    'System default': {
      'es': 'Predeterminado del sistema',
      'fr': 'DÃ©faut du systÃ¨me',
      'de': 'Systemstandard',
      'it': 'Predefinito di sistema',
      'pt': 'PadrÃ£o do sistema',
      'ar': 'Ø§ÙØªØ±Ø§Ø¶ÙŠ Ø§Ù„Ù†Ø¸Ø§Ù…',
      'hi': 'à¤¸à¤¿à¤¸à¥à¤Ÿà¤® à¤¡à¤¿à¤«à¤¼à¥‰à¤²à¥à¤Ÿ',
      'zh': 'ç³»ç»Ÿé»˜è®¤',
      'ja': 'ã‚·ã‚¹ãƒ†ãƒ ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ',
      'ko': 'ì‹œìŠ¤í…œ ê¸°ë³¸ê°’',
      'ru': 'Ð¡Ð¸ÑÑ‚ÐµÐ¼Ð½Ñ‹Ð¹ Ð¿Ð¾ ÑƒÐ¼Ð¾Ð»Ñ‡Ð°Ð½Ð¸ÑŽ',
      'tr': 'Sistem varsayÄ±lanÄ±',
    },
    'Change password': {
      'es': 'Cambiar contraseÃ±a',
      'fr': 'Changer le mot de passe',
      'de': 'Passwort Ã¤ndern',
      'it': 'Cambia password',
      'pt': 'Alterar senha',
      'ar': 'ØªØºÙŠÙŠØ± ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
      'hi': 'à¤ªà¤¾à¤¸à¤µà¤°à¥à¤¡ à¤¬à¤¦à¤²à¥‡à¤‚',
      'zh': 'æ›´æ”¹å¯†ç ',
      'ja': 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰å¤‰æ›´',
      'ko': 'ë¹„ë°€ë²ˆí˜¸ ë³€ê²½',
      'ru': 'Ð˜Ð·Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ',
      'tr': 'Åžifre deÄŸiÅŸtir',
    },
    'Send a reset link to your email': {
      'es': 'EnvÃ­a un enlace de restablecimiento a tu correo',
      'fr': 'Envoyer un lien de rÃ©initialisation Ã  votre email',
      'de': 'Sende einen Reset-Link an deine E-Mail',
      'it': 'Invia un link di ripristino alla tua email',
      'pt': 'Enviar um link de redefiniÃ§Ã£o para o seu email',
      'ar': 'Ø£Ø±Ø³Ù„ Ø±Ø§Ø¨Ø· Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙŠÙŠÙ† Ø¥Ù„Ù‰ Ø¨Ø±ÙŠØ¯Ùƒ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
      'hi': 'à¤…à¤ªà¤¨à¥€ à¤ˆà¤®à¥‡à¤² à¤ªà¤° à¤°à¥€à¤¸à¥‡à¤Ÿ à¤²à¤¿à¤‚à¤• à¤­à¥‡à¤œà¥‡à¤‚',
      'zh': 'å‘é€é‡ç½®é“¾æŽ¥åˆ°æ‚¨çš„é‚®ç®±',
      'ja': 'ãƒ¡ãƒ¼ãƒ«ã«ãƒªã‚»ãƒƒãƒˆãƒªãƒ³ã‚¯ã‚’é€ä¿¡',
      'ko': 'ì´ë©”ì¼ë¡œ ìž¬ì„¤ì • ë§í¬ ë³´ë‚´ê¸°',
      'ru': 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ ÑÑÑ‹Ð»ÐºÑƒ ÑÐ±Ñ€Ð¾ÑÐ° Ð½Ð° Ð¿Ð¾Ñ‡Ñ‚Ñƒ',
      'tr': 'E-postanÄ±za sÄ±fÄ±rlama baÄŸlantÄ±sÄ± gÃ¶nderin',
    },
    'Log out': {
      'es': 'Cerrar sesiÃ³n',
      'fr': 'Se dÃ©connecter',
      'de': 'Abmelden',
      'it': 'Disconnettersi',
      'pt': 'Sair',
      'ar': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
      'hi': 'à¤²à¥‰à¤— à¤†à¤‰à¤Ÿ',
      'zh': 'é€€å‡ºç™»å½•',
      'ja': 'ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
      'ko': 'ë¡œê·¸ì•„ì›ƒ',
      'ru': 'Ð’Ñ‹Ð¹Ñ‚Ð¸',
      'tr': 'Ã‡Ä±kÄ±ÅŸ yap',
    },
    'Sign out of your account': {
      'es': 'Cerrar sesiÃ³n de tu cuenta',
      'fr': 'Se dÃ©connecter de votre compte',
      'de': 'Von deinem Konto abmelden',
      'it': 'Disconnettersi dal proprio account',
      'pt': 'Sair da sua conta',
      'ar': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬ Ù…Ù† Ø­Ø³Ø§Ø¨Ùƒ',
      'hi': 'à¤…à¤ªà¤¨à¥‡ à¤–à¤¾à¤¤à¥‡ à¤¸à¥‡ à¤¸à¤¾à¤‡à¤¨ à¤†à¤‰à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'zh': 'é€€å‡ºæ‚¨çš„è´¦æˆ·',
      'ja': 'ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã‹ã‚‰ã‚µã‚¤ãƒ³ã‚¢ã‚¦ãƒˆ',
      'ko': 'ê³„ì •ì—ì„œ ë¡œê·¸ì•„ì›ƒ',
      'ru': 'Ð’Ñ‹Ð¹Ñ‚Ð¸ Ð¸Ð· Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚Ð°',
      'tr': 'HesabÄ±nÄ±zdan Ã§Ä±kÄ±ÅŸ yapÄ±n',
    },
    'Help & Support': {
      'es': 'Ayuda y Soporte',
      'fr': 'Aide et Support',
      'de': 'Hilfe & Support',
      'it': 'Aiuto e Supporto',
      'pt': 'Ajuda e Suporte',
      'ar': 'Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯Ø© ÙˆØ§Ù„Ø¯Ø¹Ù…',
      'hi': 'à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤”à¤° à¤¸à¤®à¤°à¥à¤¥à¤¨',
      'zh': 'å¸®åŠ©ä¸Žæ”¯æŒ',
      'ja': 'ãƒ˜ãƒ«ãƒ—ï¼†ã‚µãƒãƒ¼ãƒˆ',
      'ko': 'ë„ì›€ë§ ë° ì§€ì›',
      'ru': 'ÐŸÐ¾Ð¼Ð¾Ñ‰ÑŒ Ð¸ Ð¿Ð¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ°',
      'tr': 'YardÄ±m ve Destek',
    },
    'Contact support and app guidance': {
      'es': 'Contacta soporte y guÃ­a de la app',
      'fr': 'Contacter le support et guide de l\'app',
      'de': 'Support kontaktieren und App-Anleitung',
      'it': 'Contatta il supporto e guida all\'app',
      'pt': 'Entre em contato com o suporte e guia do app',
      'ar': 'ØªÙˆØ§ØµÙ„ Ù…Ø¹ Ø§Ù„Ø¯Ø¹Ù… ÙˆØ¥Ø±Ø´Ø§Ø¯Ø§Øª Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
      'hi': 'à¤¸à¤®à¤°à¥à¤¥à¤¨ à¤”à¤° à¤à¤ª à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¨ à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚',
      'zh': 'è”ç³»æ”¯æŒå’Œåº”ç”¨æŒ‡å—',
      'ja': 'ã‚µãƒãƒ¼ãƒˆã¸ã®å•ã„åˆã‚ã›ã¨ã‚¢ãƒ—ãƒªã‚¬ã‚¤ãƒ‰',
      'ko': 'ì§€ì› ë¬¸ì˜ ë° ì•± ì•ˆë‚´',
      'ru': 'Ð¡Ð²ÑÐ·Ð°Ñ‚ÑŒÑÑ Ñ Ð¿Ð¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ¾Ð¹ Ð¸ Ñ€ÑƒÐºÐ¾Ð²Ð¾Ð´ÑÑ‚Ð²Ð¾ Ð¿Ð¾ Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸ÑŽ',
      'tr': 'Destekle iletiÅŸim ve uygulama rehberi',
    },
    'About app': {
      'es': 'Acerca de la app',
      'fr': 'Ã€ propos de l\'app',
      'de': 'Ãœber die App',
      'it': 'Informazioni sull\'app',
      'pt': 'Sobre o app',
      'ar': 'Ø­ÙˆÙ„ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
      'hi': 'à¤à¤ª à¤•à¥‡ à¤¬à¤¾à¤°à¥‡ à¤®à¥‡à¤‚',
      'zh': 'å…³äºŽåº”ç”¨',
      'ja': 'ã‚¢ãƒ—ãƒªã«ã¤ã„ã¦',
      'ko': 'ì•± ì •ë³´',
      'ru': 'Ðž Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ð¸',
      'tr': 'Uygulama hakkÄ±nda',
    },
    'Version and legal details': {
      'es': 'VersiÃ³n y detalles legales',
      'fr': 'Version et dÃ©tails lÃ©gaux',
      'de': 'Version und rechtliche Angaben',
      'it': 'Versione e dettagli legali',
      'pt': 'VersÃ£o e detalhes legais',
      'ar': 'Ø§Ù„Ø¥ØµØ¯Ø§Ø± ÙˆØ§Ù„ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ù‚Ø§Ù†ÙˆÙ†ÙŠØ©',
      'hi': 'à¤¸à¤‚à¤¸à¥à¤•à¤°à¤£ à¤”à¤° à¤•à¤¾à¤¨à¥‚à¤¨à¥€ à¤µà¤¿à¤µà¤°à¤£',
      'zh': 'ç‰ˆæœ¬å’Œæ³•å¾‹è¯¦æƒ…',
      'ja': 'ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã¨æ³•çš„è©³ç´°',
      'ko': 'ë²„ì „ ë° ë²•ì  ì„¸ë¶€ì‚¬í•­',
      'ru': 'Ð’ÐµÑ€ÑÐ¸Ñ Ð¸ Ð¿Ñ€Ð°Ð²Ð¾Ð²Ñ‹Ðµ ÑÐ²ÐµÐ´ÐµÐ½Ð¸Ñ',
      'tr': 'SÃ¼rÃ¼m ve yasal ayrÄ±ntÄ±lar',
    },
    'Sign Out': {
      'es': 'Cerrar SesiÃ³n',
      'fr': 'DÃ©connexion',
      'de': 'Abmelden',
      'it': 'Disconnettersi',
      'pt': 'Sair',
      'ar': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
      'hi': 'à¤¸à¤¾à¤‡à¤¨ à¤†à¤‰à¤Ÿ',
      'zh': 'é€€å‡ºç™»å½•',
      'ja': 'ã‚µã‚¤ãƒ³ã‚¢ã‚¦ãƒˆ',
      'ko': 'ë¡œê·¸ì•„ì›ƒ',
      'ru': 'Ð’Ñ‹Ð¹Ñ‚Ð¸',
      'tr': 'Ã‡Ä±kÄ±ÅŸ Yap',
    },
    // â”€â”€ Missing progress/health-calc keys â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'logs': {
      'es': 'registros',
      'fr': 'entrÃ©es',
      'de': 'EintrÃ¤ge',
      'it': 'voci',
      'pt': 'registros',
      'ar': 'Ø³Ø¬Ù„Ø§Øª',
      'hi': 'à¤ªà¥à¤°à¤µà¤¿à¤·à¥à¤Ÿà¤¿à¤¯à¤¾à¤‚',
      'zh': 'è®°å½•',
      'ja': 'è¨˜éŒ²',
      'ko': 'í•­ëª©',
      'ru': 'Ð·Ð°Ð¿Ð¸ÑÐµÐ¹',
      'tr': 'kayÄ±t',
    },
    'kg left to lose to reach your goal': {
      'es': 'kg restantes por perder para alcanzar tu objetivo',
      'fr': 'kg Ã  perdre pour atteindre votre objectif',
      'de': 'kg noch abzunehmen bis zum Ziel',
      'it': 'kg da perdere per raggiungere il tuo obiettivo',
      'pt': 'kg restantes para perder e alcanÃ§ar sua meta',
      'ar': 'ÙƒØ¬Ù… Ù…ØªØ¨Ù‚ÙŠØ© Ù„Ø®Ø³Ø§Ø±ØªÙ‡Ø§ Ù„Ù„ÙˆØµÙˆÙ„ Ø¥Ù„Ù‰ Ù‡Ø¯ÙÙƒ',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯ à¤¤à¤• à¤ªà¤¹à¥à¤à¤šà¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤”à¤° à¤˜à¤Ÿà¤¾à¤¨à¥‡ à¤µà¤¾à¤²à¤¾ à¤•à¤¿à¤—à¥à¤°à¤¾',
      'zh': 'è·ç›®æ ‡è¿˜éœ€å‡é‡çš„åƒå…‹',
      'ja': 'ç›®æ¨™é”æˆã¾ã§æ®‹ã‚Šæ¸›é‡kg',
      'ko': 'ëª©í‘œ ë‹¬ì„±ê¹Œì§€ ê°ëŸ‰í•´ì•¼ í•  kg',
      'ru': 'ÐºÐ³ Ð¾ÑÑ‚Ð°Ð»Ð¾ÑÑŒ ÑÐ±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ Ð´Ð¾ Ð´Ð¾ÑÑ‚Ð¸Ð¶ÐµÐ½Ð¸Ñ Ñ†ÐµÐ»Ð¸',
      'tr': 'hedefe ulaÅŸmak iÃ§in kaybedilmesi gereken kg',
    },
    'kg left to gain to reach your goal': {
      'es': 'kg restantes por ganar para alcanzar tu objetivo',
      'fr': 'kg Ã  prendre pour atteindre votre objectif',
      'de': 'kg noch zuzunehmen bis zum Ziel',
      'it': 'kg da guadagnare per raggiungere il tuo obiettivo',
      'pt': 'kg restantes para ganhar e alcanÃ§ar sua meta',
      'ar': 'ÙƒØ¬Ù… Ù…ØªØ¨Ù‚ÙŠØ© Ù„Ø§ÙƒØªØ³Ø§Ø¨Ù‡Ø§ Ù„Ù„ÙˆØµÙˆÙ„ Ø¥Ù„Ù‰ Ù‡Ø¯ÙÙƒ',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯ à¤¤à¤• à¤ªà¤¹à¥à¤à¤šà¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤”à¤° à¤¬à¤¢à¤¼à¤¾à¤¨à¥‡ à¤µà¤¾à¤²à¤¾ à¤•à¤¿à¤—à¥à¤°à¤¾',
      'zh': 'è·ç›®æ ‡è¿˜éœ€å¢žé‡çš„åƒå…‹',
      'ja': 'ç›®æ¨™é”æˆã¾ã§æ®‹ã‚Šå¢—é‡kg',
      'ko': 'ëª©í‘œ ë‹¬ì„±ê¹Œì§€ ëŠ˜ë ¤ì•¼ í•  kg',
      'ru': 'ÐºÐ³ Ð¾ÑÑ‚Ð°Ð»Ð¾ÑÑŒ Ð½Ð°Ð±Ñ€Ð°Ñ‚ÑŒ Ð´Ð¾ Ð´Ð¾ÑÑ‚Ð¸Ð¶ÐµÐ½Ð¸Ñ Ñ†ÐµÐ»Ð¸',
      'tr': 'hedefe ulaÅŸmak iÃ§in kazanÄ±lmasÄ± gereken kg',
    },
    'Healthy Range': {
      'es': 'Rango Saludable',
      'fr': 'Plage Saine',
      'de': 'Gesunder Bereich',
      'it': 'Intervallo Sano',
      'pt': 'Faixa SaudÃ¡vel',
      'ar': 'Ø§Ù„Ù†Ø·Ø§Ù‚ Ø§Ù„ØµØ­ÙŠ',
      'hi': 'à¤¸à¥à¤µà¤¸à¥à¤¥ à¤¸à¥€à¤®à¤¾',
      'zh': 'å¥åº·èŒƒå›´',
      'ja': 'å¥åº·ç¯„å›²',
      'ko': 'ê±´ê°• ë²”ìœ„',
      'ru': 'Ð—Ð´Ð¾Ñ€Ð¾Ð²Ñ‹Ð¹ Ð´Ð¸Ð°Ð¿Ð°Ð·Ð¾Ð½',
      'tr': 'SaÄŸlÄ±klÄ± AralÄ±k',
    },
    'Goal': {
      'es': 'Objetivo',
      'fr': 'Objectif',
      'de': 'Ziel',
      'it': 'Obiettivo',
      'pt': 'Meta',
      'ar': 'Ø§Ù„Ù‡Ø¯Ù',
      'hi': 'à¤²à¤•à¥à¤·à¥à¤¯',
      'zh': 'ç›®æ ‡',
      'ja': 'ç›®æ¨™',
      'ko': 'ëª©í‘œ',
      'ru': 'Ð¦ÐµÐ»ÑŒ',
      'tr': 'Hedef',
    },
    // â”€â”€ AI Scan Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'AI Food Scanner': {'es':'EscÃ¡ner de Alimentos IA','fr':'Scanner IA de Nourriture','de':'KI-Lebensmittelscanner','it':'Scanner IA Alimenti','pt':'Scanner IA de Alimentos','ar':'Ù…Ø§Ø³Ø­ Ø§Ù„Ø·Ø¹Ø§Ù… Ø¨Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ','hi':'AI à¤«à¥‚à¤¡ à¤¸à¥à¤•à¥ˆà¤¨à¤°','zh':'AIé£Ÿç‰©æ‰«æä»ª','ja':'AIé£Ÿå“ã‚¹ã‚­ãƒ£ãƒŠãƒ¼','ko':'AI ìŒì‹ ìŠ¤ìºë„ˆ','ru':'Ð˜Ð˜ Ð¡ÐºÐ°Ð½ÐµÑ€ ÐµÐ´Ñ‹','tr':'Yapay Zeka Yemek TarayÄ±cÄ±'},
    'Scan your meal': {'es':'Escanea tu comida','fr':'Scannez votre repas','de':'Mahlzeit scannen','it':'Scansiona il tuo pasto','pt':'Escaneie sua refeiÃ§Ã£o','ar':'Ø§Ù…Ø³Ø­ ÙˆØ¬Ø¨ØªÙƒ Ø¶ÙˆØ¦ÙŠÙ‹Ø§','hi':'à¤…à¤ªà¤¨à¤¾ à¤­à¥‹à¤œà¤¨ à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤°à¥‡à¤‚','zh':'æ‰«ææ‚¨çš„é¤é£Ÿ','ja':'é£Ÿäº‹ã‚’ã‚¹ã‚­ãƒ£ãƒ³','ko':'ì‹ì‚¬ ìŠ¤ìº”í•˜ê¸°','ru':'Ð¡ÐºÐ°Ð½Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ Ð±Ð»ÑŽÐ´Ð¾','tr':'YemeÄŸini tara'},
    'Use the AI scanner to identify calories, macros and portion size. Capture the meal from above and make sure it is well lit.': {'es':'Usa el escÃ¡ner IA para identificar calorÃ­as, macros y tamaÃ±o de porciÃ³n.','fr':"Utilisez le scanner IA pour identifier les calories, les macros et la taille des portions.",'de':'Verwenden Sie den KI-Scanner, um Kalorien, MakronÃ¤hrstoffe und PortionsgrÃ¶ÃŸen zu erkennen.','it':"Usa lo scanner IA per identificare calorie, macro e dimensione della porzione.",'pt':'Use o scanner IA para identificar calorias, macros e tamanho da porÃ§Ã£o.','ar':'Ø§Ø³ØªØ®Ø¯Ù… Ø§Ù„Ù…Ø§Ø³Ø­ Ù„Ù„ØªØ¹Ø±Ù Ø¹Ù„Ù‰ Ø§Ù„Ø³Ø¹Ø±Ø§Øª ÙˆØ§Ù„Ù…ØºØ°ÙŠØ§Øª ÙˆØ­Ø¬Ù… Ø§Ù„Ø­ØµØ©.','hi':'à¤•à¥ˆà¤²à¥‹à¤°à¥€, à¤®à¥ˆà¤•à¥à¤°à¥‹ à¤”à¤° à¤­à¤¾à¤— à¤ªà¤¹à¤šà¤¾à¤¨à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ AI à¤¸à¥à¤•à¥ˆà¤¨à¤° à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¥‡à¤‚à¥¤','zh':'ä½¿ç”¨AIæ‰«æä»ªè¯†åˆ«å¡è·¯é‡Œã€å®é‡è¥å…»ç´ å’Œä»½é‡ã€‚','ja':'AIã‚¹ã‚­ãƒ£ãƒŠãƒ¼ã§ã‚«ãƒ­ãƒªãƒ¼ã€ãƒžã‚¯ãƒ­ã€ãƒãƒ¼ã‚·ãƒ§ãƒ³ã‚µã‚¤ã‚ºã‚’è­˜åˆ¥ã—ã¾ã™ã€‚','ko':'AI ìŠ¤ìºë„ˆë¡œ ì¹¼ë¡œë¦¬, ë§¤í¬ë¡œ, 1íšŒ ì œê³µëŸ‰ì„ íŒŒì•…í•˜ì„¸ìš”.','ru':'Ð˜ÑÐ¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Ð˜Ð˜-ÑÐºÐ°Ð½ÐµÑ€ Ð´Ð»Ñ Ð¾Ð¿Ñ€ÐµÐ´ÐµÐ»ÐµÐ½Ð¸Ñ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¹, Ð¼Ð°ÐºÑ€Ð¾ÑÐ¾Ð² Ð¸ Ñ€Ð°Ð·Ð¼ÐµÑ€Ð° Ð¿Ð¾Ñ€Ñ†Ð¸Ð¸.','tr':'Kalori, makro ve porsiyon boyutunu belirlemek iÃ§in AI tarayÄ±cÄ±yÄ± kullanÄ±n.'},
    'Food Preview': {'es':'Vista Previa de Alimento','fr':'AperÃ§u de la Nourriture','de':'Lebensmittelvorschau','it':'Anteprima Cibo','pt':'PrÃ©-visualizaÃ§Ã£o do Alimento','ar':'Ù…Ø¹Ø§ÙŠÙ†Ø© Ø§Ù„Ø·Ø¹Ø§Ù…','hi':'à¤–à¤¾à¤¨à¥‡ à¤•à¤¾ à¤ªà¥‚à¤°à¥à¤µà¤¾à¤µà¤²à¥‹à¤•à¤¨','zh':'é£Ÿç‰©é¢„è§ˆ','ja':'é£Ÿå“ãƒ—ãƒ¬ãƒ“ãƒ¥ãƒ¼','ko':'ìŒì‹ ë¯¸ë¦¬ë³´ê¸°','ru':'ÐŸÑ€ÐµÐ´Ð¿Ñ€Ð¾ÑÐ¼Ð¾Ñ‚Ñ€ Ð±Ð»ÑŽÐ´Ð°','tr':'Yemek Ã–nizleme'},
    'No image selected yet. Tap the camera button to capture your meal.': {'es':'Sin imagen. Toca el botÃ³n de cÃ¡mara.','fr':"Aucune image. Appuyez sur l'appareil photo.",'de':'Kein Bild. Kamera antippen.','it':'Nessuna immagine. Tocca la fotocamera.','pt':'Sem imagem. Toque na cÃ¢mera.','ar':'Ù„Ø§ ØªÙˆØ¬Ø¯ ØµÙˆØ±Ø©. Ø§Ø¶ØºØ· Ø¹Ù„Ù‰ Ø§Ù„ÙƒØ§Ù…ÙŠØ±Ø§.','hi':'à¤•à¥‹à¤ˆ à¤›à¤µà¤¿ à¤¨à¤¹à¥€à¤‚à¥¤ à¤•à¥ˆà¤®à¤°à¤¾ à¤¬à¤Ÿà¤¨ à¤¦à¤¬à¤¾à¤à¤‚à¥¤','zh':'æ— å›¾ç‰‡ã€‚ç‚¹å‡»ç›¸æœºæŒ‰é’®ã€‚','ja':'ç”»åƒãªã—ã€‚ã‚«ãƒ¡ãƒ©ã‚’ã‚¿ãƒƒãƒ—ã€‚','ko':'ì´ë¯¸ì§€ ì—†ìŒ. ì¹´ë©”ë¼ ë²„íŠ¼ íƒ­.','ru':'ÐÐµÑ‚ Ð¸Ð·Ð¾Ð±Ñ€Ð°Ð¶ÐµÐ½Ð¸Ñ. ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ ÐºÐ°Ð¼ÐµÑ€Ñƒ.','tr':'GÃ¶rsel yok. Kamera dÃ¼ÄŸmesine dokun.'},
    'Take Picture': {'es':'Tomar Foto','fr':'Prendre une Photo','de':'Foto aufnehmen','it':'Scatta Foto','pt':'Tirar Foto','ar':'Ø§Ù„ØªÙ‚Ø§Ø· ØµÙˆØ±Ø©','hi':'à¤¤à¤¸à¥à¤µà¥€à¤° à¤²à¥‡à¤‚','zh':'æ‹ç…§','ja':'å†™çœŸã‚’æ’®ã‚‹','ko':'ì‚¬ì§„ ì°ê¸°','ru':'Ð¡Ð´ÐµÐ»Ð°Ñ‚ÑŒ Ñ„Ð¾Ñ‚Ð¾','tr':'FotoÄŸraf Ã§ek'},
    'Gallery': {'es':'GalerÃ­a','fr':'Galerie','de':'Galerie','it':'Galleria','pt':'Galeria','ar':'Ø§Ù„Ù…Ø¹Ø±Ø¶','hi':'à¤—à¥ˆà¤²à¤°à¥€','zh':'ç›¸å†Œ','ja':'ã‚®ãƒ£ãƒ©ãƒªãƒ¼','ko':'ê°¤ëŸ¬ë¦¬','ru':'Ð“Ð°Ð»ÐµÑ€ÐµÑ','tr':'Galeri'},
    'Analyze Food': {'es':'Analizar Alimento','fr':'Analyser les Aliments','de':'Essen analysieren','it':'Analizza Cibo','pt':'Analisar Alimento','ar':'ØªØ­Ù„ÙŠÙ„ Ø§Ù„Ø·Ø¹Ø§Ù…','hi':'à¤–à¤¾à¤¨à¤¾ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤•à¤°à¥‡à¤‚','zh':'åˆ†æžé£Ÿç‰©','ja':'é£Ÿå“ã‚’åˆ†æž','ko':'ìŒì‹ ë¶„ì„','ru':'ÐÐ½Ð°Ð»Ð¸Ð·Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ ÐµÐ´Ñƒ','tr':'YemeÄŸi Analiz Et'},
    // â”€â”€ Water Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Daily Water Goal': {'es':'Meta Diaria de Agua','fr':"Objectif d'Eau Quotidien",'de':'TÃ¤gliches Wasserziel','it':'Obiettivo Idrico Giornaliero','pt':'Meta DiÃ¡ria de Ãgua','ar':'Ù‡Ø¯Ù Ø§Ù„Ù…Ø§Ø¡ Ø§Ù„ÙŠÙˆÙ…ÙŠ','hi':'à¤¦à¥ˆà¤¨à¤¿à¤• à¤ªà¤¾à¤¨à¥€ à¤•à¤¾ à¤²à¤•à¥à¤·à¥à¤¯','zh':'æ¯æ—¥é¥®æ°´ç›®æ ‡','ja':'1æ—¥ã®æ°´åˆ†ç›®æ¨™','ko':'ì¼ì¼ ë¬¼ ëª©í‘œ','ru':'Ð”Ð½ÐµÐ²Ð½Ð°Ñ Ð½Ð¾Ñ€Ð¼Ð° Ð²Ð¾Ð´Ñ‹','tr':'GÃ¼nlÃ¼k Su Hedefi'},
    'Remove Water': {'es':'Eliminar Agua','fr':"Retirer de l'Eau",'de':'Wasser entfernen','it':'Rimuovi Acqua','pt':'Remover Ãgua','ar':'Ø¥Ø²Ø§Ù„Ø© Ø§Ù„Ù…Ø§Ø¡','hi':'à¤ªà¤¾à¤¨à¥€ à¤¹à¤Ÿà¤¾à¤à¤‚','zh':'å‡å°‘æ°´é‡','ja':'æ°´ã‚’æ¸›ã‚‰ã™','ko':'ë¬¼ ì œê±°','ru':'Ð£Ð±Ñ€Ð°Ñ‚ÑŒ Ð²Ð¾Ð´Ñƒ','tr':'Su Ã‡Ä±kar'},
    'Remove': {'es':'Eliminar','fr':'Supprimer','de':'Entfernen','it':'Rimuovi','pt':'Remover','ar':'Ø¥Ø²Ø§Ù„Ø©','hi':'à¤¹à¤Ÿà¤¾à¤à¤‚','zh':'ç§»é™¤','ja':'å‰Šé™¤','ko':'ì œê±°','ru':'Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ','tr':'KaldÄ±r'},
    'Select Date': {'es':'Seleccionar Fecha','fr':'SÃ©lectionner une Date','de':'Datum auswÃ¤hlen','it':'Seleziona Data','pt':'Selecionar Data','ar':'Ø§Ø®ØªØ± Ø§Ù„ØªØ§Ø±ÙŠØ®','hi':'à¤¤à¤¾à¤°à¥€à¤– à¤šà¥à¤¨à¥‡à¤‚','zh':'é€‰æ‹©æ—¥æœŸ','ja':'æ—¥ä»˜ã‚’é¸æŠž','ko':'ë‚ ì§œ ì„ íƒ','ru':'Ð’Ñ‹Ð±Ñ€Ð°Ñ‚ÑŒ Ð´Ð°Ñ‚Ñƒ','tr':'Tarih SeÃ§'},
    'Edit Goal': {'es':'Editar Meta','fr':"Modifier l'Objectif",'de':'Ziel bearbeiten','it':'Modifica Obiettivo','pt':'Editar Meta','ar':'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù‡Ø¯Ù','hi':'à¤²à¤•à¥à¤·à¥à¤¯ à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¥‡à¤‚','zh':'ç¼–è¾‘ç›®æ ‡','ja':'ç›®æ¨™ã‚’ç·¨é›†','ko':'ëª©í‘œ ìˆ˜ì •','ru':'Ð˜Ð·Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ñ†ÐµÐ»ÑŒ','tr':'Hedefi DÃ¼zenle'},
    "Today's Intake": {'es':'Consumo de Hoy','fr':"Consommation d'Aujourd'hui",'de':'Heutige Aufnahme','it':'Assunzione di Oggi','pt':'IngestÃ£o de Hoje','ar':'Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ Ø§Ù„ÙŠÙˆÙ…','hi':'à¤†à¤œ à¤•à¤¾ à¤¸à¥‡à¤µà¤¨','zh':'ä»Šæ—¥æ‘„å…¥','ja':'ä»Šæ—¥ã®æ‘‚å–é‡','ko':'ì˜¤ëŠ˜ì˜ ì„­ì·¨ëŸ‰','ru':'Ð¡ÐµÐ³Ð¾Ð´Ð½ÑÑˆÐ½ÐµÐµ Ð¿Ð¾Ñ‚Ñ€ÐµÐ±Ð»ÐµÐ½Ð¸Ðµ','tr':'BugÃ¼nkÃ¼ AlÄ±m'},
    'Weekly Hydration Graph': {'es':'GrÃ¡fico de HidrataciÃ³n Semanal','fr':"Graphique d'Hydratation Hebdomadaire",'de':'WÃ¶chentliches Hydratationsdiagramm','it':'Grafico Idratazione Settimanale','pt':'GrÃ¡fico de HidrataÃ§Ã£o Semanal','ar':'Ø±Ø³Ù… Ø¨ÙŠØ§Ù†ÙŠ Ù„Ù„ØªØ±Ø·ÙŠØ¨ Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹ÙŠ','hi':'à¤¸à¤¾à¤ªà¥à¤¤à¤¾à¤¹à¤¿à¤• à¤œà¤²à¤¯à¥‹à¤œà¤¨ à¤—à¥à¤°à¤¾à¤«','zh':'æ¯å‘¨è¡¥æ°´å›¾è¡¨','ja':'é€±é–“æ°´åˆ†è£œçµ¦ã‚°ãƒ©ãƒ•','ko':'ì£¼ê°„ ìˆ˜ë¶„ ì„­ì·¨ ê·¸ëž˜í”„','ru':'Ð“Ñ€Ð°Ñ„Ð¸Ðº Ð³Ð¸Ð´Ñ€Ð°Ñ‚Ð°Ñ†Ð¸Ð¸ Ð·Ð° Ð½ÐµÐ´ÐµÐ»ÑŽ','tr':'HaftalÄ±k Hidrasyon GrafiÄŸi'},
    'Tap any bar to view logged water intake for that date.': {'es':'Toca cualquier barra para ver el agua registrada.','fr':"Appuyez sur une barre pour voir l'apport enregistrÃ©.",'de':'Balken antippen, um Wasseraufnahme anzuzeigen.','it':"Tocca qualsiasi barra per vedere l'apporto registrato.",'pt':'Toque em qualquer barra para ver a ingestÃ£o de Ã¡gua.','ar':'Ø§Ø¶ØºØ· Ø¹Ù„Ù‰ Ø£ÙŠ Ø´Ø±ÙŠØ· Ù„Ø¹Ø±Ø¶ ÙƒÙ…ÙŠØ© Ø§Ù„Ù…Ø§Ø¡ Ø§Ù„Ù…Ø³Ø¬Ù„Ø©.','hi':'à¤•à¤¿à¤¸à¥€ à¤¬à¤¾à¤° à¤ªà¤° à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚à¥¤','zh':'ç‚¹å‡»ä»»æ„æŸ±å½¢æŸ¥çœ‹è®°å½•ã€‚','ja':'ãƒãƒ¼ã‚’ã‚¿ãƒƒãƒ—ã—ã¦è¨˜éŒ²ã‚’è¡¨ç¤ºã€‚','ko':'ë§‰ëŒ€ë¥¼ íƒ­í•˜ì„¸ìš”.','ru':'ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ Ð½Ð° ÑÑ‚Ð¾Ð»Ð±ÐµÑ† Ð´Ð»Ñ Ð¿Ñ€Ð¾ÑÐ¼Ð¾Ñ‚Ñ€Ð°.','tr':'Herhangi bir Ã§ubuÄŸa dokun.'},
    // â”€â”€ Calories Detail Screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    'Calories Tracker': {'es':'Rastreador de CalorÃ­as','fr':'Suivi des Calories','de':'Kalorienverfolgung','it':'Tracker Calorie','pt':'Rastreador de Calorias','ar':'Ù…ØªØªØ¨Ø¹ Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ©','hi':'à¤•à¥ˆà¤²à¥‹à¤°à¥€ à¤Ÿà¥à¤°à¥ˆà¤•à¤°','zh':'å¡è·¯é‡Œè¿½è¸ªå™¨','ja':'ã‚«ãƒ­ãƒªãƒ¼ãƒˆãƒ©ãƒƒã‚«ãƒ¼','ko':'ì¹¼ë¡œë¦¬ íŠ¸ëž˜ì»¤','ru':'Ð¢Ñ€ÐµÐºÐµÑ€ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¹','tr':'Kalori TakipÃ§isi'},
    'Pick Any Date': {'es':'Elegir Cualquier Fecha','fr':"Choisir N'importe Quelle Date",'de':'Beliebiges Datum wÃ¤hlen','it':'Scegli Qualsiasi Data','pt':'Escolher Qualquer Data','ar':'Ø§Ø®ØªØ± Ø£ÙŠ ØªØ§Ø±ÙŠØ®','hi':'à¤•à¥‹à¤ˆ à¤­à¥€ à¤¤à¤¾à¤°à¥€à¤– à¤šà¥à¤¨à¥‡à¤‚','zh':'é€‰æ‹©ä»»æ„æ—¥æœŸ','ja':'ä»»æ„ã®æ—¥ä»˜ã‚’é¸æŠž','ko':'ë‚ ì§œ ì„ íƒ','ru':'Ð’Ñ‹Ð±Ñ€Ð°Ñ‚ÑŒ Ð»ÑŽÐ±ÑƒÑŽ Ð´Ð°Ñ‚Ñƒ','tr':'Herhangi Bir Tarih SeÃ§'},
    'Meals Logged': {'es':'Comidas Registradas','fr':'Repas EnregistrÃ©s','de':'Aufgezeichnete Mahlzeiten','it':'Pasti Registrati','pt':'RefeiÃ§Ãµes Registradas','ar':'Ø§Ù„ÙˆØ¬Ø¨Ø§Øª Ø§Ù„Ù…Ø³Ø¬Ù„Ø©','hi':'à¤¦à¤°à¥à¤œ à¤•à¤¿à¤ à¤—à¤ à¤­à¥‹à¤œà¤¨','zh':'å·²è®°å½•é¤é£Ÿ','ja':'è¨˜éŒ²ã•ã‚ŒãŸé£Ÿäº‹','ko':'ê¸°ë¡ëœ ì‹ì‚¬','ru':'Ð—Ð°Ð¿Ð¸ÑÐ°Ð½Ð½Ñ‹Ðµ Ð¿Ñ€Ð¸Ñ‘Ð¼Ñ‹ Ð¿Ð¸Ñ‰Ð¸','tr':'KayÄ±tlÄ± Ã–ÄŸÃ¼nler'},
    'items': {'es':'elementos','fr':'Ã©lÃ©ments','de':'EintrÃ¤ge','it':'voci','pt':'itens','ar':'Ø¹Ù†Ø§ØµØ±','hi':'à¤†à¤‡à¤Ÿà¤®','zh':'é¡¹ç›®','ja':'ä»¶','ko':'í•­ëª©','ru':'Ð·Ð°Ð¿Ð¸ÑÐµÐ¹','tr':'Ã¶ÄŸe'},
    'Calorie Summary': {'es':'Resumen de CalorÃ­as','fr':'RÃ©sumÃ© des Calories','de':'KalorienÃ¼bersicht','it':'Riepilogo Calorie','pt':'Resumo de Calorias','ar':'Ù…Ù„Ø®Øµ Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ©','hi':'à¤•à¥ˆà¤²à¥‹à¤°à¥€ à¤¸à¤¾à¤°à¤¾à¤‚à¤¶','zh':'å¡è·¯é‡Œæ‘˜è¦','ja':'ã‚«ãƒ­ãƒªãƒ¼ã‚µãƒžãƒªãƒ¼','ko':'ì¹¼ë¡œë¦¬ ìš”ì•½','ru':'Ð¡Ð²Ð¾Ð´ÐºÐ° ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¹','tr':'Kalori Ã–zeti'},
    'Weekly Calorie Intake': {'es':'Ingesta Semanal de CalorÃ­as','fr':'Apport Calorique Hebdomadaire','de':'WÃ¶chentliche Kalorienaufnahme','it':'Apporto Calorico Settimanale','pt':'IngestÃ£o Semanal de Calorias','ar':'Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ© Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹ÙŠ','hi':'à¤¸à¤¾à¤ªà¥à¤¤à¤¾à¤¹à¤¿à¤• à¤•à¥ˆà¤²à¥‹à¤°à¥€ à¤¸à¥‡à¤µà¤¨','zh':'æ¯å‘¨å¡è·¯é‡Œæ‘„å…¥','ja':'é€±é–“ã‚«ãƒ­ãƒªãƒ¼æ‘‚å–é‡','ko':'ì£¼ê°„ ì¹¼ë¡œë¦¬ ì„­ì·¨ëŸ‰','ru':'ÐÐµÐ´ÐµÐ»ÑŒÐ½Ð¾Ðµ Ð¿Ð¾Ñ‚Ñ€ÐµÐ±Ð»ÐµÐ½Ð¸Ðµ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¹','tr':'HaftalÄ±k Kalori AlÄ±mÄ±'},
    'No meals logged for': {'es':'No hay comidas registradas para','fr':'Aucun repas enregistrÃ© pour','de':'Keine Mahlzeiten aufgezeichnet fÃ¼r','it':'Nessun pasto registrato per','pt':'Nenhuma refeiÃ§Ã£o registrada para','ar':'Ù„Ø§ ØªÙˆØ¬Ø¯ ÙˆØ¬Ø¨Ø§Øª Ù…Ø³Ø¬Ù„Ø© Ù„Ù€','hi':'à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥‹à¤ˆ à¤­à¥‹à¤œà¤¨ à¤¦à¤°à¥à¤œ à¤¨à¤¹à¥€à¤‚','zh':'æ— å·²è®°å½•é¤é£Ÿï¼Œæ—¥æœŸï¼š','ja':'é£Ÿäº‹è¨˜éŒ²ãªã—ï¼š','ko':'ê¸°ë¡ëœ ì‹ì‚¬ ì—†ìŒ:','ru':'ÐŸÑ€Ð¸Ñ‘Ð¼Ñ‹ Ð¿Ð¸Ñ‰Ð¸ Ð½Ðµ Ð·Ð°Ð¿Ð¸ÑÐ°Ð½Ñ‹ Ð·Ð°','tr':'KayÄ±tlÄ± Ã¶ÄŸÃ¼n yok:'},
    'Daily Calorie Challenge': {'es':'DesafÃ­o CalÃ³rico Diario','fr':'DÃ©fi Calorique Quotidien','de':'TÃ¤gliche Kalorienherausforderung','it':'Sfida Calorica Giornaliera','pt':'Desafio CalÃ³rico DiÃ¡rio','ar':'ØªØ­Ø¯ÙŠ Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ© Ø§Ù„ÙŠÙˆÙ…ÙŠ','hi':'à¤¦à¥ˆà¤¨à¤¿à¤• à¤•à¥ˆà¤²à¥‹à¤°à¥€ à¤šà¥à¤¨à¥Œà¤¤à¥€','zh':'æ¯æ—¥å¡è·¯é‡ŒæŒ‘æˆ˜','ja':'æ¯Žæ—¥ã®ã‚«ãƒ­ãƒªãƒ¼ãƒãƒ£ãƒ¬ãƒ³ã‚¸','ko':'ì¼ì¼ ì¹¼ë¡œë¦¬ ì±Œë¦°ì§€','ru':'Ð•Ð¶ÐµÐ´Ð½ÐµÐ²Ð½Ñ‹Ð¹ ÐºÐ°Ð»Ð¾Ñ€Ð¸Ð¹Ð½Ñ‹Ð¹ Ð²Ñ‹Ð·Ð¾Ð²','tr':'GÃ¼nlÃ¼k Kalori Meydan OkumasÄ±'},
    "Today's Quests": {'es':'Misiones de Hoy','fr':"QuÃªtes d'Aujourd'hui",'de':'Heutige Quests','it':'Missioni di Oggi','pt':'MissÃµes de Hoje','ar':'Ù…Ù‡Ø§Ù… Ø§Ù„ÙŠÙˆÙ…','hi':'à¤†à¤œ à¤•à¥‡ à¤•à¥à¤µà¥‡à¤¸à¥à¤Ÿ','zh':'ä»Šæ—¥ä»»åŠ¡','ja':'ä»Šæ—¥ã®ã‚¯ã‚¨ã‚¹ãƒˆ','ko':'ì˜¤ëŠ˜ì˜ í€˜ìŠ¤íŠ¸','ru':'Ð¡ÐµÐ³Ð¾Ð´Ð½ÑÑˆÐ½Ð¸Ðµ Ð·Ð°Ð´Ð°Ð½Ð¸Ñ','tr':'BugÃ¼nÃ¼n GÃ¶revleri'},
    'Hit Calorie Target': {'es':'Alcanzar el Objetivo de CalorÃ­as','fr':"Atteindre l'Objectif Calorique",'de':'Kalorienziel erreichen','it':'Raggiungere il Target Calorico','pt':'Atingir a Meta de Calorias','ar':'ØªØ­Ù‚ÙŠÙ‚ Ù‡Ø¯Ù Ø§Ù„Ø³Ø¹Ø±Ø§Øª Ø§Ù„Ø­Ø±Ø§Ø±ÙŠØ©','hi':'à¤•à¥ˆà¤²à¥‹à¤°à¥€ à¤²à¤•à¥à¤·à¥à¤¯ à¤¹à¤¾à¤¸à¤¿à¤² à¤•à¤°à¥‡à¤‚','zh':'è¾¾æˆå¡è·¯é‡Œç›®æ ‡','ja':'ã‚«ãƒ­ãƒªãƒ¼ç›®æ¨™ã‚’é”æˆ','ko':'ì¹¼ë¡œë¦¬ ëª©í‘œ ë‹¬ì„±','ru':'Ð”Ð¾ÑÑ‚Ð¸Ñ‡ÑŒ Ñ†ÐµÐ»Ð¸ Ð¿Ð¾ ÐºÐ°Ð»Ð¾Ñ€Ð¸ÑÐ¼','tr':'Kalori Hedefine UlaÅŸ'},
    'Stay within 80% - 110% of daily goal': {'es':'Mantente dentro del 80% - 110% de la meta diaria','fr':"Restez dans 80% - 110% de l'objectif quotidien",'de':'Bleiben Sie innerhalb von 80% - 110% des Tagesziels','it':"Rimani nell'80% - 110% dell'obiettivo giornaliero",'pt':'Mantenha-se entre 80% - 110% da meta diÃ¡ria','ar':'Ø§Ø¨Ù‚ ÙÙŠ Ù†Ø·Ø§Ù‚ 80% - 110% Ù…Ù† Ù‡Ø¯ÙÙƒ Ø§Ù„ÙŠÙˆÙ…ÙŠ','hi':'à¤¦à¥ˆà¤¨à¤¿à¤• à¤²à¤•à¥à¤·à¥à¤¯ à¤•à¥‡ 80% - 110% à¤•à¥‡ à¤­à¥€à¤¤à¤° à¤°à¤¹à¥‡à¤‚','zh':'ä¿æŒåœ¨æ¯æ—¥ç›®æ ‡çš„80%-110%ä¹‹é—´','ja':'1æ—¥ã®ç›®æ¨™ã®80%ï½ž110%ä»¥å†…ã«åŽã‚ã‚‹','ko':'ì¼ì¼ ëª©í‘œì˜ 80%~110% ì´ë‚´ë¡œ ìœ ì§€','ru':'ÐžÑÑ‚Ð°Ð²Ð°Ð¹Ñ‚ÐµÑÑŒ Ð² Ð¿Ñ€ÐµÐ´ÐµÐ»Ð°Ñ… 80% - 110% Ð¾Ñ‚ Ð´Ð½ÐµÐ²Ð½Ð¾Ð¹ Ñ†ÐµÐ»Ð¸','tr':'GÃ¼nlÃ¼k hedefin %80 - %110 aralÄ±ÄŸÄ±nda kal'},
    'Log 3+ Meals': {'es':'Registrar 3+ Comidas','fr':'Enregistrer 3+ Repas','de':'3+ Mahlzeiten aufzeichnen','it':'Registra 3+ Pasti','pt':'Registrar 3+ RefeiÃ§Ãµes','ar':'ØªØ³Ø¬ÙŠÙ„ 3 ÙˆØ¬Ø¨Ø§Øª Ø£Ùˆ Ø£ÙƒØ«Ø±','hi':'3+ à¤­à¥‹à¤œà¤¨ à¤²à¥‰à¤— à¤•à¤°à¥‡à¤‚','zh':'è®°å½•3é¤ä»¥ä¸Š','ja':'3é£Ÿä»¥ä¸Šè¨˜éŒ²ã™ã‚‹','ko':'3ë¼ ì´ìƒ ê¸°ë¡í•˜ê¸°','ru':'Ð—Ð°Ð¿Ð¸ÑÐ°Ñ‚ÑŒ 3+ Ð¿Ñ€Ð¸Ñ‘Ð¼Ð° Ð¿Ð¸Ñ‰Ð¸','tr':'3+ Ã–ÄŸÃ¼n Kaydet'},
    'Track Breakfast, Lunch & Dinner': {'es':'Registrar Desayuno, Almuerzo y Cena','fr':'Suivre le Petit-dÃ©jeuner, le DÃ©jeuner et le DÃ®ner','de':'FrÃ¼hstÃ¼ck, Mittagessen & Abendessen verfolgen','it':'Registra Colazione, Pranzo e Cena','pt':'Registrar CafÃ© da ManhÃ£, AlmoÃ§o e Jantar','ar':'ØªØªØ¨Ø¹ Ø§Ù„Ø¥ÙØ·Ø§Ø± ÙˆØ§Ù„ØºØ¯Ø§Ø¡ ÙˆØ§Ù„Ø¹Ø´Ø§Ø¡','hi':'à¤¨à¤¾à¤¶à¥à¤¤à¤¾, à¤¦à¥‹à¤ªà¤¹à¤° à¤”à¤° à¤°à¤¾à¤¤ à¤•à¤¾ à¤–à¤¾à¤¨à¤¾ à¤Ÿà¥à¤°à¥ˆà¤• à¤•à¤°à¥‡à¤‚','zh':'è¿½è¸ªæ—©é¤ã€åˆé¤å’Œæ™šé¤','ja':'æœé£Ÿã€æ˜¼é£Ÿã€å¤•é£Ÿã‚’è¨˜éŒ²ã™ã‚‹','ko':'ì•„ì¹¨, ì ì‹¬, ì €ë… ê¸°ë¡í•˜ê¸°','ru':'Ð—Ð°Ð¿Ð¸ÑÑ‹Ð²Ð°Ð¹Ñ‚Ðµ Ð·Ð°Ð²Ñ‚Ñ€Ð°Ðº, Ð¾Ð±ÐµÐ´ Ð¸ ÑƒÐ¶Ð¸Ð½','tr':'KahvaltÄ±, Ã–ÄŸle ve AkÅŸam YemeÄŸi Takibi'},  };
}

