// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnaCMA6qqmYnCLVBJyBBWnpnLRCtXDwNA',
    appId: '1:176029163069:web:7872c6f59d1d4c22bd9454',
    messagingSenderId: '176029163069',
    projectId: 'ai-calorie-counter-1dd12',
    authDomain: 'ai-calorie-counter-1dd12.firebaseapp.com',
    storageBucket: 'ai-calorie-counter-1dd12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtjmhXFm20CdcCH7uVMpNxB8nIK2B1tM',
    appId: '1:176029163069:android:52faddbc122214aabd9454',
    messagingSenderId: '176029163069',
    projectId: 'ai-calorie-counter-1dd12',
    storageBucket: 'ai-calorie-counter-1dd12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcPQDxXzZpH4JxAIaesoRmT5c2eezrq0',
    appId: '1:176029163069:ios:d90df22a3e29a7eabd9454',
    messagingSenderId: '176029163069',
    projectId: 'ai-calorie-counter-1dd12',
    storageBucket: 'ai-calorie-counter-1dd12.firebasestorage.app',
    iosBundleId: 'com.example.aiCalorieCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcPQDxXzZpH4JxAIaesoRmT5c2eezrq0',
    appId: '1:176029163069:ios:d90df22a3e29a7eabd9454',
    messagingSenderId: '176029163069',
    projectId: 'ai-calorie-counter-1dd12',
    storageBucket: 'ai-calorie-counter-1dd12.firebasestorage.app',
    iosBundleId: 'com.example.aiCalorieCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnaCMA6qqmYnCLVBJyBBWnpnLRCtXDwNA',
    appId: '1:176029163069:web:b0427c963f703917bd9454',
    messagingSenderId: '176029163069',
    projectId: 'ai-calorie-counter-1dd12',
    authDomain: 'ai-calorie-counter-1dd12.firebaseapp.com',
    storageBucket: 'ai-calorie-counter-1dd12.firebasestorage.app',
  );
}
